argotorg/fe

Cargo.lock, Cargo.toml, compiler/Cargo.toml, compiler/src/abi/json.rs, compiler/src/abi/json_builder.rs, compiler/src/abi/mod.rs, compiler/src/errors.rs, compiler/src/evm/mod.rs, compiler/src/evm/solc_temp.json, compiler/src/lib.rs, compiler/src/yul/ast_builder.rs, compiler/src/yul/base.rs, compiler/src/yul/constructor.rs, compiler/src/yul/mod.rs, compiler/src/yul/selectors.rs, compiler/tests/fixtures/guest_book.vy, compiler/tests/fixtures/simple_contract.vy, compiler/tests/fixtures/simple_map.vy, compiler/tests/test_evm.rs
Part of #10.
*It's probably best to review this after #15 and #16 get merged, since those are included.*
This includes an `evm` module which uses the solc Rust bindings to compile Yul into bytecode. It also has a test that deploys a simple contract onto the EVM and interacts with it using the ABI produced by the `abi` module.
=> Bytecode compiler and EVM tests

Cargo.lock, Cargo.toml, compiler/Cargo.toml, compiler/src/errors.rs, compiler/src/lib.rs, compiler/src/yul/ast_builder.rs, compiler/src/yul/base.rs, compiler/src/yul/constructor.rs, compiler/src/yul/mod.rs, compiler/src/yul/selectors.rs
Part of #10.
This includes just enough functionality to compile a contract like this:
```
contract Foo:
pub def bar(x: u256) -> u256:
return x
```
To keep it simple, types are basically ignored (everyting is `u256`) and all variables are stored on the stack. There are some `Scope` data structures in here as well, which aren't necessary for it to work, but would be worth reviewing as I intend to build more complexity on top of them.
The Yul code generated by the compiler would not actually be runnable, since it doesn't have the ABI builder from #15 to generate the selector switch from. In #17, I add that to this module and demonstrate that the contract can be deployed and ran in a test.
=> Basic Yul compiler

.github/workflows/main.yml, Cargo.lock, compiler/Cargo.toml, compiler/src/yul/mappers/assignments.rs, compiler/src/yul/mappers/expressions.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/return_addition_u256.vy, compiler/tests/fixtures/return_division_u256.vy, compiler/tests/fixtures/return_multiplication_u256.vy, compiler/tests/fixtures/return_subtraction_u256.vy
As stated in #24 we need to add support for basic arithmetic operations.
- Resolving binary expressions for `add`, `sub`, `mul`, `div` to their YUL counterparts
- Added tests in expressions, assignments as well as evm_contracts.
=> Add support for basic arithmetic operations

spec/index.md
As I continue to dive deeper I realized that beginning with the language specification might actually be one of the most valuable things we can do. It ensures everyone is working towards a common, shared vision of the language rather than "making things up as we go".
I think that by writing the language specification early on, we sooner get to the point where we create some value for the community. Even if we don't have anything that compiles, just having the spec alone and be able to gather community feedback is a great benefit in itself.
This builds on top of #40 
This is very incomplete and I'm sure it has tons of box. I'm leaning heavily on the  [Rust reference](https://doc.rust-lang.org/stable/reference/introduction.html) for structure and syntax of the document (We love you Rust …
=> More specifications

compiler/src/abi/builder.rs, compiler/src/abi/elements.rs, compiler/src/yul/mappers/declarations.rs, compiler/src/yul/namespace/types.rs, compiler/tests/fixtures/multi_param.vy, compiler/tests/fixtures/return_addition_u256.vy, compiler/tests/fixtures/return_array.vy, compiler/tests/fixtures/return_bitwiseand_u256.vy, compiler/tests/fixtures/return_bitwiseor_u256.vy, compiler/tests/fixtures/return_bitwiseshl_u256.vy, compiler/tests/fixtures/return_bitwiseshr_u256.vy, compiler/tests/fixtures/return_bitwisexor_u256.vy, compiler/tests/fixtures/return_division_u256.vy, compiler/tests/fixtures/return_mod_u256.vy, compiler/tests/fixtures/return_multiplication_u256.vy, compiler/tests/fixtures/return_pow_u256.vy, compiler/tests/fixtures/return_sender.vy, compiler/tests/fixtures/return_subtraction_u256.vy, compiler/tests/fixtures/return_u256.vy, compiler/tests/fixtures/u256_u256_map.vy, parser/src/parsers.rs, parser/tests/fixtures/tokenizer/validator_registration.v.py.json
We decided to follow rust by renaming `uint256` to `u256` so the tokenizer needed to be changed.
Changed tokenizer + tests to use `u256` instead of `uint256`
=> Rename uint256 to u256 according to spec update

compiler/src/abi/builder.rs, compiler/src/abi/elements.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/namespace/types.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/return_eq_u256.fe, compiler/tests/fixtures/return_gt_u256.fe, compiler/tests/fixtures/return_gte_u256.fe, compiler/tests/fixtures/return_lt_u256.fe, compiler/tests/fixtures/return_lte_u256.fe, compiler/tests/fixtures/return_noteq_u256.fe, spec/index.md
We do not yet map various comparison expressions (e.g. `==`, `!=` etc)
1. Had to add support for `bool` in various places (I'm being vague because I don't always exactly now yet what I'm doing :joy: )
2. Mapped expressions to their YUL counterparts which for some expressions meant to generate chained calls where the result of one opcode is the input to an `iszero` call
3. Updated the spec
=> Map comparision operators

README.md
There was no link to the draft spec yet
Added link in the readme
=> Link to spec from Readme

.github/workflows/main.yml, Cargo.lock, Cargo.toml, compiler/src/evm/mod.rs
As described in #32, CI does currently not run the tests that compile actual Fe contracts. That's because running these tests depends on compiling `solc-rust` which is time consuming and requires certain system dependencies. Obviously, this is a problem and its not just tests, linting doesn't run over the entire code base either for this reason.
1. Install `libboost-all-dev` system dependency
2. Setup caching for build artifacts (based on `Cargo.lock`)
3. Introduce `solc-backend` flag to the main project and pass it down
4. Run tests with `solc-backend` enabled.
As we can see in the test runs of this PR, jobs run still very fast with 2 - 3 m (except after Christmas / NYE when cache eviction policy kicked in because no one sent PRs for 7 straight days)
[//]: # (Stay ahead of things, add …
=> Make CI run with solc-backend

.github/workflows/main.yml
We only test against Linux
Added support for Mac
=> Run CI against Mac

.github/workflows/main.yml
There's a problem preventing serde from being cachable.
Exclude it from caching.
=> Exclude serde from caching

compiler/src/yul/mappers/functions.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/revert.fe, semantics/src/traversal/functions.rs, spec/index.md
We need to have support for `revert` expressions.
1. Refactored `test_function` into two functions in order to re-use it for revert assertion
2. Mapped  `revert` to `revert(0,0)` in YUL (Ignoring revert reasons #75 for now)
3. Added a contract test for revert
4. Added coverage for `revert` in the spec
=> Implement revert

compiler/src/evm/mod.rs, compiler/src/yul/mod.rs, src/main_full.rs
There's currently no way to instruct the compiler to show the internal representation of Tokens or AST for a given code snippet. Being able to emit these can be beneficial for learning purposes and debugging.
- Unrelated but included in this PR: Map `-e`, `-o` to `--emit` and `--output-dir`
- add support for `ast` and `tokens` target
- internal changed the yul compiler from only emitting the bare yul str to emitting a `CompilerOutput`
```rust
pub struct CompilerOutput {
pub tokens: String,
pub ast: String,
pub yul: String,
}
```
=> Support AST and Tokens as output targets

compiler/src/errors.rs, compiler/src/yul/mappers/expressions.rs, compiler/tests/compile_errors.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/compile_errors/return_call_to_fn_without_return.fe, compiler/tests/fixtures/return_u256_from_called_fn.fe, semantics/src/errors.rs, semantics/src/traversal/expressions.rs, semantics/src/traversal/functions.rs
We currently do not support call expressions (e.g. `return self.foo()`)
- mapped the `expr_call` in the mapper
- in the semantic pass, check if the called function does have a return value and raise a `TypeError` if not
- Added a fixture contract to test the success case
- Started a new category of fixture tests that check for compile errors and added a fixture for the described error case
=> Implement call expressions

compiler/src/yul/mappers/assignments.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/mappers/mod.rs, compiler/src/yul/mappers/operations.rs, compiler/src/yul/runtime/abi.rs, compiler/src/yul/runtime/functions.rs, compiler/tests/erc20.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/nested_map.fe, compiler/tests/fixtures/return_sender.fe, semantics/src/lib.rs, semantics/src/namespace/operations.rs, semantics/src/namespace/types.rs, semantics/src/traversal/assignments.rs, semantics/src/traversal/expressions.rs, semantics/tests/analysis.rs, spec/index.md
closes #77 
We weren't able to compile maps with nested map values.
There's a file I added named [operations](https://github.com/ethereum/fe/blob/fed15791844da5717a4c1c5bf4f14feeeb71a2d1/compiler/src/yul/mappers/operations.rs) that should be used to form basic Yul operations. I'll follow up this PR with another that addresses #19 (the issue is a bit outdated) and moves the Yul code generation taking place in the semantic library to the operations module. This is mentioned briefly in #39:
> There are still some things that need to be refactored, but for the sake of keeping this PR at a reasonable size, they were ignored. The best example of this is that we still use methods defined within our types module to form Yul expressions and statements. These Yul elements should instead be formed …
=> Nested maps

compiler/src/yul/mappers/assignments.rs, compiler/src/yul/mappers/declarations.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/mappers/functions.rs, compiler/src/yul/mappers/operations.rs, compiler/tests/evm_contracts.rs, semantics/src/namespace/types.rs
Partially addresses #19 and something that was mentioned in #39.
> There are still some things that need to be refactored, but for the sake of keeping this PR at a reasonable size, they were ignored. The best example of this is that we still use methods defined within our types module to form Yul expressions and statements. These Yul elements should instead be formed exclusively in the mapper pass. 
Created a new [`FeSized` trait](https://github.com/ethereum/fe/blob/f67359d68d63f4a8885a22a067654143d4174d1b/semantics/src/namespace/types.rs#L8) that is analogous to Rust's very own [`Sized` trait](https://doc.rust-lang.org/beta/std/marker/trait.Sized.html), then used this trait to implement a set of [data operations](https://github.com/ethereum/fe/blob/80486998c0fdc41fd31eb223ea2b72ed0b24cb59 …
=> FeSized trait and data opertions.

compiler/src/yul/mappers/expressions.rs, compiler/src/yul/mappers/functions.rs, compiler/tests/compile_errors.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/compile_errors/return_call_to_fn_with_param_type_mismatch.fe, compiler/tests/fixtures/return_u256_from_called_fn_with_args.fe, semantics/src/traversal/_utils.rs, semantics/src/traversal/expressions.rs, semantics/src/traversal/functions.rs, semantics/src/traversal/mod.rs
As mentioned in #89 we do currently not have support for arguments in call expressions.
- Resolving the arguments with `expr`
- for that, I had to manually span them reusing the span that is around the `CallArg`
- manually built a `yul::Expression::FunctionCall` as I'm not sure how to do that using a macro.
- Added a test that demonstrates the various ways of using arguments in call expressions
=> Support for arguments in call expressions.

compiler/src/yul/mappers/expressions.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/return_bool_false.fe, compiler/tests/fixtures/return_bool_true.fe, parser/src/ast.rs, parser/src/parsers.rs, semantics/src/traversal/expressions.rs
Fe does currently not support returning boolean literals. The following won't parse:
```
contract Foo:
pub def bar() -> bool:
return false
```
1. Added a new expression type `Bool`
2. Changed the parser to map the literals `true`  and `false` to the `Bool` expression
3. Added handling for the new expression in semantic and mapper pass
=> Add support for returning boolean literal

compiler/src/yul/mappers/contracts.rs, compiler/src/yul/operations.rs, compiler/src/yul/runtime/abi.rs, compiler/src/yul/runtime/functions.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/events.fe, semantics/src/lib.rs, semantics/src/namespace/scopes.rs, semantics/src/namespace/types.rs, semantics/src/traversal/contracts.rs, semantics/src/traversal/expressions.rs, semantics/src/traversal/functions.rs
closes #87 
Events had very limited support. Basically, you could only emit events with a single `bytes` parameter.
Added ABI encoding for any combination of values and hooked this into event emits.
When an event definition is encountered, an encoding operation is created for the given set of parameters. This encoding operation is then used whenever an event is emitted. The same thing is done with public functions and their external returns.
Here are the encoding operations generated for [events.fe](https://github.com/ethereum/fe/blob/285025b167f0361664f51d0bc53b3cb97c79e11a/compiler/tests/fixtures/events.fe):
```
function abi_encode_uint256_address_uint256_bytes100(val_0, val_1, val_2, val_3) -> ptr
{
ptr := avail()
pop(alloc_mstoren(val_0, 32))
pop(alloc_mstoren(val_1, 32)) …
```
=> Support for events with multiple params.

.github/workflows/main.yml
CI is [currently failing for Mac Builds](https://github.com/ethereum/fe/pull/106/checks?check_run_id=1322145918)
1. Pin to an older rust nightly
2. Pin to an older Mac Version
None of that worked.
Disabled Mac for the lack of a better fix :cry: 
=> Disable MacOS builds on CI

Cargo.lock, compiler/Cargo.toml, compiler/tests/evm_contracts.rs
We were using rust-evm version 0.14, which is a few months old.
Updated to the most recent version (0.18).
=> Updated rust-evm

compiler/tests/compile_errors.rs, compiler/tests/fixtures/compile_errors/mismatch_return_type.fe, compiler/tests/fixtures/compile_errors/missing_return.fe, compiler/tests/fixtures/compile_errors/unexpected_return.fe, parser/src/span.rs, semantics/src/errors.rs, semantics/src/lib.rs, semantics/src/namespace/scopes.rs, semantics/src/traversal/assignments.rs, semantics/src/traversal/declarations.rs, semantics/src/traversal/expressions.rs, semantics/src/traversal/functions.rs
Fixes #104
As explained in #104 we do currently not score well in terms of return value checking. We do not detect when:
1  A method is defined with return value but does not return any value
2. A method is defined with a return value but the actual returned value doesn't match the signature
3. A method is defined to **not** return a value but does return a value
For case 1 and 3, I added checks directly from `func_def` to scan if all code paths return or revert (or the opposite)
For case 2 I gave `func_return` access to the `FunctionAttributes` of the host function to perform type checking
=> Validate return values of function body

compiler/src/evm/mod.rs, compiler/tests/compile_errors.rs, compiler/tests/evm_contracts.rs, src/main_full.rs
Sometimes, especially during development, we would like to inspect a piece of generated YUL code even if it is invalid, meaning that we can not derive proper bytecode from it.
Naturally one would think that by using `<path-to-fe-file> --emit yul` instead of `<path-to-fe-file> --emit yul, bytecode` we could simply remove the request for compiling to bytecode to see the faulty YUL code. But that's not how the internals of the compiler work up to now because compilation is currently an all-or-nothing operation. 
1. The compile module got support for a new `CompileStage` enum that controls if we should stop after generating YUL (which currently implies generating tokens and AST) or generate everything up to the bytecode
2. The CLI only uses `CompileStage::AllUpToBytecode` only if the …
=> Allow compile to YUL even when YUL is invalid

compiler/src/abi/builder.rs, compiler/src/yul/mappers/assignments.rs, compiler/src/yul/mappers/declarations.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/mappers/functions.rs, compiler/src/yul/operations.rs, compiler/src/yul/runtime/abi.rs, compiler/tests/compile_errors.rs, parser/src/ast.rs, semantics/src/errors.rs, semantics/src/lib.rs, semantics/src/namespace/operations.rs, semantics/src/namespace/scopes.rs, semantics/src/namespace/types.rs, semantics/src/traversal/contracts.rs, semantics/src/traversal/declarations.rs, semantics/src/traversal/expressions.rs, semantics/src/traversal/functions.rs
Currently, functions that do not return anything are a special case from the perspective of the type system. There is no way to capture anything from a call to such functions. In fact, a call to a function that does not return anything is treated as a semantic error.
E.g.
```
contract Foo:
def child():
y = 1
def parent():
x = self.child()  # semantic error
```
We [recently discussed](https://github.com/ethereum/fe/pull/103#discussion_r514078077) to change this and follow the model of rust which treats any function that does not explicitly return a value as one that returns an empty tuple `()`.
The core motivation for that is that it generalizes the handling of functions by getting rid of different branching logic based on whether a function does or does not return a value. In the new …
=> Implicitly return empty tuple when nothing else is returned

compiler/src/yul/mappers/_utils.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/mappers/functions.rs, compiler/src/yul/mappers/mod.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/call_statement_with_args.fe, compiler/tests/fixtures/call_statement_with_args_2.fe, compiler/tests/fixtures/call_statement_without_args.fe, semantics/src/namespace/types.rs, semantics/src/traversal/functions.rs
closes #92 
As stated in  #92, we do currently not have support for call statements (e.g. `self.assign(10, 11)`. 
This is based on #111
- Moved `spanned_expression` helper into _utils module
- Mapped `fe::FuncStmt::Expr` to either the expression directly or to `pop([expr])` in case the return type is anything else than `()`
- In the semantic pass, I just analyzed the `fe::FuncStmt::Expr` as any other expression.
- A few helpers to ease checking for `()` type
=> Implement call statements

compiler/src/yul/mappers/functions.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/assert.fe, semantics/src/traversal/functions.rs
closes #86 
We did not support assert statements.
Added support for assert statements. This does not include support for revert messages if the assert fails.
For example, the message in the statement `assert x > 5, "not greater than five"` will just be ignored. We can add this after basic string support is implemented, but it's not necessarily required for the Fe erc20 contract.
=> Assert statements.

compiler/src/yul/mod.rs
The generated AST and tokens are all in one giant line.
Using the build in `#?` pretty printing we get some decent formatting.
=> Pretty print tokens and AST in --emit

README.md, deploy-website.sh
We don't have a site up that hosts our docs. Unfortunately, getting our docs up on https://docs.rs isn't so simple because our Git dependencies make it impossible to get Fe on https://crates.io which would be needed to host the docs on docs.rs.
Fortunately, we can still use `cargo docs` to generate the docs and host the site ourselves.
1. Created a shell script `deploy-website.sh` that takes care of generating the site and pushing its contents into the `gh-pages` branch of this repo. This is an orphaned branch simply to host the artifacts of the generated site. This is a one-click-deploy-no-questions-asked deployment. Assuming one uses `upstream` to point to this repo, invoking `deploy-website.sh` is all it takes to update the live site.
2. A few minor fixes to the Readme.
The site is …
=> Add deploy script for docs

src/_utils/mod.rs, src/main.rs, src/main_full.rs
Inspecting generated YUL code is currently no fun.
If we run this on current master `cargo run --features solc-backend compiler/tests/fixtures/return_addition_u256.fe --emit yul`.
We get a file with these contents:
```
object \"Contract\" { code { let size := datasize(\"runtime\") datacopy(0, dataoffset(\"runtime\"), size) return(0, size) } object \"runtime\" { code { function bar(x, y) -> return_val { let ptr := avail() { return_val := add(x, y) leave } free(ptr) } function avail() -> ptr { ptr := mload(0x00) if eq(ptr, 0x00) { ptr := 0x20 } } function alloc(size) -> ptr { ptr := mload(0x00) if eq(ptr, 0x00) { ptr := 0x20 } mstore(0x00, add(ptr, size)) } function alloc_mstoren(val, size) -> ptr { ptr := alloc(size) mstoren(ptr, val, size) } function free(ptr) { mstore(0x00, ptr) } …
```
=> Pretty print YUL code

compiler/src/yul/mappers/functions.rs, compiler/tests/compile_errors.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/compile_errors/missing_return_in_else.fe, compiler/tests/fixtures/compile_errors/strict_boolean_if_else.fe, compiler/tests/fixtures/if_statement.fe, compiler/tests/fixtures/if_statement_2.fe, semantics/src/traversal/functions.rs
Fe does currently not support `if` / `else`  statements.
1. Added support by mapping to the equivalent switch block in YUL
2. Added a check in the semantic pass that the tested expression is of type `Base::Bool`
3. Changed the `validate_all_paths_return_or_revert` check to follow down the branches of `if` / `else` to ensure all paths `return` or `revert`
4. Added a bunch of test cases to cover the functionality.
=> Add support for if / else statements

Cargo.lock, compiler/src/yul/mappers/functions.rs, compiler/tests/compile_errors.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/compile_errors/not_in_scope.fe, compiler/tests/fixtures/compile_errors/not_in_scope_2.fe, compiler/tests/fixtures/if_statement_with_block_declaration.fe, compiler/tests/fixtures/while_loop.fe, semantics/src/namespace/scopes.rs, semantics/src/traversal/assignments.rs, semantics/src/traversal/declarations.rs, semantics/src/traversal/expressions.rs, semantics/src/traversal/functions.rs
We do not yet support while loops. Additionally, there were two problems regarding scoping rules:
1. Declarations within block scopes did not work because statements in if/else or while loops where not semantically checked which also means declarations where not respected.
2. After the previous problem was fixed it became obvious that declarations where not properly scoped with block scoping rules. Instead, they were attributed to the enclosing function scope. While this is inline with Python, we like to diverge from Python here to follow rust (or JS/TS `let` scoping rules for that matter) scoping rules which introduces a new scope for each block.
**While Loop Support**
- This builds on top of #116 (because it has some needed helpers)
- Semantic pass
- refactored repetitive code into …
=> Add support for while loops

compiler/src/yul/mappers/functions.rs, compiler/tests/compile_errors.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/compile_errors/break_without_loop.fe, compiler/tests/fixtures/compile_errors/break_without_loop_2.fe, compiler/tests/fixtures/while_loop_with_break.fe, compiler/tests/fixtures/while_loop_with_break_2.fe, semantics/src/errors.rs, semantics/src/namespace/scopes.rs, semantics/src/traversal/functions.rs
We don't support `break` statements yet.
1. Added a new `BlockScopeType` to `BlockScope` that can be one of `Function`, `IfElse` or `Loop`.
2. Added `pub fn inherits_type(&self, typ: BlockScopeType) -> bool` to `BlockScope` to be able to tell if certain statements (e.g. `break`, `continue`) can be used within the current scope or not.
3. Semantic pass checks with `inherits_type` if placement is ok and returns `SemanticError::BreakWithoutLoop` if not
4. Mapper pass maps `break` to YUL
=> Implement support for break statement

semantics/src/namespace/scopes.rs, semantics/src/traversal/expressions.rs, semantics/src/traversal/functions.rs
We had mixed use of `Rc<T>` with some places using `ptr.clone()` and whereas others used `Rc::clone(&ptr)`.
Change to use the idiomatic syntax preferred by the official Rust book.
Further reading:
https://github.com/rust-lang/rust/pull/42137#issuecomment-304908345
https://github.com/nical/rfcs/blob/rc-newref-clone/text/0000-rc-newref-clone.md
=> Use Rc::clone(&ptr) syntax instead of ptr.clone()

compiler/src/yul/mappers/functions.rs, compiler/tests/compile_errors.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/compile_errors/continue_without_loop.fe, compiler/tests/fixtures/compile_errors/continue_without_loop_2.fe, compiler/tests/fixtures/while_loop_with_continue.fe, semantics/src/errors.rs, semantics/src/traversal/functions.rs
We do not support the `continue` statement yet.
- Semantic pass checks that `continue` is used within loop
- Mapper pass maps to YUL
- Added tests to cover functionality as well as raised error on misplaced use
=> Implement support for continue statement

compiler/src/yul/mappers/expressions.rs, compiler/src/yul/runtime/functions.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/ternary_expression.fe, parser/src/ast.rs, parser/src/parsers.rs, parser/tests/fixtures/parsers/expr.ron, semantics/src/traversal/expressions.rs
=> Add support for ternary expression

compiler/src/yul/mappers/assignments.rs, compiler/src/yul/mappers/declarations.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/operations.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/sized_vals_in_sto.fe, semantics/src/errors.rs, semantics/src/lib.rs, semantics/src/namespace/scopes.rs, semantics/src/namespace/types.rs, semantics/src/traversal/_utils.rs, semantics/src/traversal/assignments.rs, semantics/src/traversal/contracts.rs, semantics/src/traversal/declarations.rs, semantics/src/traversal/expressions.rs, semantics/src/traversal/functions.rs, semantics/tests/analysis.rs
Types other than `map` were not supported as contract fields.
1. Nonce values are now assigned to each contract field. For sized values, these nonces are used to generate pointers for each field during compilation.
2. Introduced explicit *moves* for expressions. Expression attributes now have an optional  `move_location` in addition to the original expression `location`. Previously, the `location` of an expression only indicated the final location after a possible implicit move. These moves are no longer implicitly defined, but are instead attributed to the expression. So instead of having something like `my_u256_array[42]` understood as a value type, it is understood as a memory pointer. If the expression is needed by the surrounding context as a value (e.g. `my_value = …
=> Sized types in storage

compiler/tests/fixtures/return_u256_from_called_fn.fe, semantics/src/namespace/scopes.rs, semantics/src/traversal/contracts.rs, semantics/src/traversal/expressions.rs, semantics/src/traversal/functions.rs
As explained in #90 we do currently have a bug that causes us to fail to compile contracts with functions that call other functions if the called function isn't defined above the calling function. In plain english: The order of function definitions matters but it should not matter.
1. `func_def` was split into two functions: `func_def` and `func_body`. The former is only concerned about checking the types of the function definition and creating a scope for the function. It does not perform any tasks on the `body`  of the function.
2. The `scope` of the function is now also preserved when calling `add_function` on the contract scope. This is to give `function_body` a clean way to resolve the (already existing) scope.
3. In `contract_def`, we add a second pass that iterates over all …
=> Split analysis of function definition and function body to ensure order of function definitions doesn't matter

compiler/src/yul/mappers/expressions.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/return_u128_cast.fe, semantics/src/errors.rs, semantics/src/lib.rs, semantics/src/traversal/expressions.rs
closes #136 
We did not support type constructors for addresses and integers.
Expressions wrapped within a type constructor are given the type defined by the constructor.
=> Type constructors

semantics/src/namespace/scopes.rs, semantics/src/namespace/types.rs, semantics/src/traversal/assignments.rs, semantics/src/traversal/contracts.rs, semantics/src/traversal/declarations.rs, semantics/src/traversal/expressions.rs, semantics/src/traversal/functions.rs, semantics/src/traversal/module.rs, semantics/src/traversal/types.rs
Multiple things:
1. `return_type` on `BlockScope` didn't feel right (because it carries no meaning for block scopes that originate in loops or if/else)
2. Using enums for `ContractDef`, `BlockDef` and `ModuleDef` made usage less ergonomic because one always had to match arms that would not make sense leaving to excessive use of `unreachable!()` or other anti patterns.
1. Instead of putting `return_type` on `BlockScope` there's now a `name` on `BlockScope` that can tie a `BlockScope` to a function name. Frankly one can argue that `name` wouldn't be strictly necessary for block scopes originating from loops or if/else but one *can* think of the benefits of naming these (e.g. `block_scope_foo_1` -> `blockscope_foo_2`) e.g. when visualizing scopes in a hierachy.
Having the name, one can …
=> Refactoring of scopes

compiler/src/abi/builder.rs, compiler/src/yul/operations.rs, compiler/tests/compile_errors.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/compile_errors/indexed_event.fe, compiler/tests/fixtures/events.fe, compiler/tests/fixtures/guest_book.fe, semantics/src/errors.rs, semantics/src/namespace/events.rs, semantics/src/traversal/contracts.rs, semantics/tests/analysis.rs, semantics/tests/fixtures/guest_book.fe
closes #138 
We were not handling indexed event parameters correctly. They were being included inside of the log data, when they should have been included as extra log topics.
This PR does not include support for indexed non-base type params.
- added indexed fields to the ABI builder
- the `idx` qualifier now affects the way events are logged
- we return an error if there are more than 3 indexed event params (no `log5` operation available)
=> Indexed event params for base types

compiler/src/yul/constructor.rs, compiler/src/yul/mappers/assignments.rs, compiler/src/yul/mappers/declarations.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/mappers/functions.rs, compiler/src/yul/mappers/mod.rs, compiler/src/yul/mod.rs, compiler/src/yul/runtime/abi_dispatcher.rs, compiler/src/yul/utils.rs, compiler/tests/fixtures/erc20_token.fe
closes #102 
Identifiers chosen by users could conflict with identifiers introduced by the compiler.
User-defined variable names now have `$` added to the front and user defined function names now have `$$` added to the front.
=> Safe user-defined identifier mapping. 

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/main.yml, .towncrier.template.md, Cargo.lock, Cargo.toml, Makefile, compiler/Cargo.toml, docs/release.md, docs/release_notes.md, newsfragments/README.md, newsfragments/validate_files.py, parser/Cargo.toml, pyproject.toml, release.toml, semantics/Cargo.toml
We didn't have a process to cut releases.
1. This adds support for towncrier so we get release notes similar to [the Trinity release notes](https://github.com/ethereum/trinity/blob/master/docs/release_notes.rst) except that they are in markdown for us
Working with towncrier is explained [here](https://github.com/ethereum/fe/tree/master/newsfragments/README.md)
2. Cutting releases is a two command process and its explained in more depth [here](https://github.com/ethereum/fe/tree/master/docs/release.md)
3. After the `make release` command Github automatically picks up the release, produces binaries and puts it on the release page.
4. The current version was moved back to `0.0.1` just so that we free up `0.1.0` for the first real release.
=> Implement release process

README.md, newsfragments/162.doc.md
It was recently broad up on Twitter that we should point to Examples right from the README.
- Pointed to ER20 demo
- Updated recently achieved goals and short-term goals
=> Update README with short term goals and examples

compiler/src/abi/elements.rs, compiler/tests/evm_contracts.rs, newsfragments/160.feature.md, src/main_full.rs
We do currently not support emitting the contract ABI. Emitting the contract ABI is crucial in order to interact with a contract.
- Added support to emit the ABI via `--emit abi`
- Changed ABI API to allow prettyfying
- Cleaned up error handling
- Made `abi,bytecode` the default value for `--emit`
=> Support emitting ABI via --emit abi

Makefile
The clippy command in the make file was outdated.
Updated so that now one can run `make lint` locally as a simple shortcut to the same checks that run in CI.
=> Update clippy command in Makefile

compiler/tests/compile_errors.rs, compiler/tests/fixtures/compile_errors/type_constructor_from_variable.fe, newsfragments/163.feature.md, semantics/src/errors.rs, semantics/src/traversal/expressions.rs
Currently, our integer type constructor are too permissive. E.g. the following is allowed today even though it isn't guaranteed that `val` will fit into the `u16)`
```
pub def bar(val: u8) -> u16:
return u16(val)
```
I believe that our integer type constructor should simply not allow being used with anything other than a numeric literal such as `1` or `-3`.
Numeric literals can be checked on compile time whereas arbitrary variables can't. 
- Added a function `validate_is_numeric_literal` and used it inside `expr_call` to validate
- Added a new error type `NumericLiteralExpected`
- Added a test to prove bad code is rejected.
Notice that this does not yet entail #145 but it is paving the way for it.
=> Ensure integer type constructor reject anything but numeric literals

compiler/src/yul/abi/functions.rs, compiler/src/yul/mappers/assignments.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/operations.rs, compiler/src/yul/runtime/functions.rs, compiler/tests/compile_errors.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/address_bytes10_map.fe, compiler/tests/fixtures/compile_errors/needs_mem_copy.fe, compiler/tests/fixtures/data_copying_stress.fe, compiler/tests/fixtures/erc20_token.fe, compiler/tests/fixtures/guest_book.fe, compiler/tests/fixtures/sized_vals_in_sto.fe, newsfragments/155.feature.md, semantics/src/builtins.rs, semantics/src/errors.rs, semantics/src/lib.rs, semantics/src/namespace/types.rs, semantics/src/traversal/assignments.rs, semantics/src/traversal/expressions.rs, semantics/src/traversal/functions.rs, semantics/tests/analysis.rs, semantics/tests/fixtures/guest_book.fe
closes #152 
- we didn't have operations for copying storage -> storage or memory -> memory
- the existing naming scheme for these operations was a bit confusing (e.g. `scopy` for storage -> memory copying)
- copy operations were going byte-by-byte, which is extremely inefficient
- implemented said copying operations and used them in the relevant places (assignments and expression moves)
- updated the existing operations with a cleaner naming scheme
- copying now happens word-by-word
=> Memory and storage copying

compiler/src/yul/mappers/assignments.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/data_copying_stress.fe
Reference type assignments were being copied, when they should be assigning a shared reference.
Removed the copy.
=> Fix assignments

compiler/src/yul/mappers/declarations.rs, compiler/tests/fixtures/data_copying_stress.fe, newsfragments/173.feature.md
Previously, this code would fail:
```
another_reference: u256[10] = my_array
```
As a workaround declaration and assignment could be split apart.
```
another_reference: u256[10]
another_reference =  = my_array
```
With this change, the shorter declaration with assignment syntax is supported.
- Added implementation to map value assignments in declarations
- Rewrote test code that used workaround
=> Add support for value assignment in declaration

semantics/src/namespace/types.rs, semantics/src/traversal/functions.rs
Tiny refeactoring to get rid of `to_fixed_size` and implement the more common `From<T>` trait instead.
=> Refactor away to_fixed_size method

.github/workflows/main.yml, Cargo.lock, compiler/Cargo.toml, newsfragments/169.internal.md
We were using an older version of solc for Yul compilation.
Went into solc-rust and updated the solidity submodule. There are still some things that I'd like to look into in solc-rust before opening a PR in that repo, so we're just using my personal fork for now.
Surprisingly, the solc-backend feature of the Fe compiler still works fine. I thought there would be atleast a couple breaking changes in libyul.
=> Updated solc to v0.8.0.

README.md, newsfragments/177.doc.md
In the recent months there were several critics brought up regarding our Readme:
1. People had a hard time finding example and generally requested to see a piece of Fe code featured in the Readme
2. The information was found to be overcrowded
3.  In #176 it was brought up that Fe should distance itself more clearly from Vyper
The Readme hasn't had much overhaul since the project was originally born as *rust-vyper*. When it was written back then, a big motivation of the Readme was to compare and explain what was back then an alternative Vyper compiler. Naturally, the Readme has a lot of phrases that can be understood as "It's like the original Vyper but xyz". This doesn't reflect the current state of the project anymore which has since moved on to become Fe.
A lot of the information was …
=> Overhaul Readme

.github/workflows/main.yml, newsfragments/178.internal.md
We currently do not test on Mac and don't produce Mac binaries on releases.
- Re-enabled running tests on Mac
- Changed release job to also build and upload Mac binary
=> Run CI tests on Mac too and create Mac binaries on releases

newsfragments/195.doc.md, spec/index.md
We were missing descriptions of these two builtin functions in the spec.
Added descriptions in the data layout section.
=> Add descriptions of to_mem and clone to spec.

compiler/tests/compile_errors.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/compile_errors/string_capacity_mismatch.fe, compiler/tests/fixtures/strings.fe, newsfragments/201.feature.md, semantics/src/errors.rs, semantics/src/lib.rs, semantics/src/namespace/scopes.rs, semantics/src/namespace/types.rs, semantics/src/traversal/expressions.rs
1. There was a bug if the same string literal was used multiple times
2. We did not have support for string casts yet (e.g. `string100("foo")`
1. Converted `Vec<String>` to `HashSet<String>`
2. Refactored part that recognize string types into a reusable `TryFrom`
3. Recognize `stringxxx` type constructors based on the `TryFrom`
4. Map string type casts to the altered expression.
=> Fix bug with string literals and add support for string casts

compiler/src/yul/operations/data.rs, compiler/src/yul/runtime/mod.rs, compiler/tests/compile_errors.rs, compiler/tests/fixtures/compile_errors/call_event_with_wrong_types.fe, compiler/tests/fixtures/strings.fe, newsfragments/202.bugfix.md, semantics/src/namespace/events.rs, semantics/src/traversal/expressions.rs, semantics/src/traversal/functions.rs
On master, the following would not raise an error even though it should:
```
contract Foo:
event MyEvent:
val_1: string100
val_2: u8
pub def foo():
emit MyEvent("foo", 1000)
```
Basically reuse the `call_arg` that is defined in `expression` and a little bit of refactoring the event to expose all field types.
=> Ensure event emits are type checked

compiler/src/abi/builder.rs, compiler/src/abi/elements.rs, compiler/src/abi/mod.rs, compiler/src/evm/mod.rs, compiler/src/lib.rs, compiler/src/types.rs, compiler/src/yul/mod.rs, compiler/tests/compile_errors.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/two_contracts.fe, newsfragments/197.feature.md, semantics/src/errors.rs, src/main.rs, src/main_full.rs
We were only able to compile the first contract in a module.
- Updated the compiler module internals and API to handle multiple contracts.
- Updated the contract testing harness and added a test for a module with two separate contracts.
- Updated the CLI. We now write the following to the output directory:
```
output
|-- Bar
|   |-- Bar.bin
|   |-- Bar_abi.json
|   `-- Bar_ir.yul
|-- Foo
|   |-- Foo.bin
|   |-- Foo_abi.json
|   `-- Foo_ir.yul
|-- module.ast
`-- module.tokens
```
=> Compile multiple contracts in single module.

.github/workflows/main.yml, Makefile
Code coverage reports don't include tests that require the solc-backend feature.
Added `--all-features` flag to the cargo tarpaulin command (and replaced the deprecated `--all` with `--workspace`).
=> Run code coverage on all features (solc-backend)

compiler/src/abi/builder.rs
The abi builder crashed on an unknown type (with a short name) in a function signature. Eg:
```
contract F:
pub def f(x: foo) -> bool:
return true
```
This presumably should have been caught by the analyzer; I haven't looked into how it slipped through the cracks.
changed `if &base[..6] == "string"` to `if base.starts_with("string")`. Other similar tests all use `starts_with` already, btw.
=> Fix crash in abi builder on unknown type with short name

compiler/src/lib.rs, newsfragments/218.feature.md
We return an error to the user when Yul compilation fails. We should be panicking.
Changed the compiler so that it panics instead of returning an error.
=> Panic if Yul compilation fails.

Cargo.lock, analyzer/Cargo.toml, analyzer/src/builtins.rs, analyzer/src/traversal/expressions.rs, compiler/src/yul/mappers/expressions.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/return_builtin_attributes.fe, compiler/tests/fixtures/return_sender.fe, newsfragments/208.feature.md
There are some missing builtins needed for the uniswap demo.
~It hasn't been yet :)
I'll probably do block.timestamp, maybe more depending on whether they raise tricky issues.~
Edit: I've added support for:
block.coinbase
block.difficulty
block.number
block.timestamp
chain.id
msg.value
tx.origin
tx.gas_price (aside: do we want to standardize on snake_case like .to_mem()?)
resolves #190
I changed the builtins to use enums, so the compiler can tell us when we aren't handling a case. I also stubbed out some probable builtins in those enums (based on the existing demo fe code, and vyper/solidity). I'm sure there are some things yet to be decided (eg is keccak256 a method on every value, or a standalone builtin function, or imported from the std library, or part of a builtin trait, or...?). …
=> Add support for chain.id, block.timestamp, other builtin attributes

analyzer/src/lib.rs, analyzer/src/namespace/operations.rs, analyzer/src/namespace/scopes.rs, analyzer/src/namespace/types.rs, analyzer/src/traversal/contracts.rs, analyzer/src/traversal/declarations.rs, analyzer/src/traversal/expressions.rs, compiler/src/yul/mappers/declarations.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/names.rs, compiler/src/yul/operations/abi.rs, compiler/src/yul/operations/calls.rs, compiler/src/yul/operations/mod.rs, compiler/src/yul/runtime/functions/calls.rs, compiler/src/yul/runtime/functions/mod.rs, compiler/src/yul/runtime/mod.rs, compiler/tests/compile_errors.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/compile_errors/external_call_type_error.fe, compiler/tests/fixtures/compile_errors/external_call_wrong_number_of_params.fe, compiler/tests/fixtures/external_contract.fe, newsfragments/204.feature.md
We were unable to make calls to external contracts.
- Added a new `Contract` type. The contract type is treated like an address, but carries extra information about the contact's public interface.
- When compiling a contract, the module scope is checked for any external contract type definitions. If an external contract type is found, a set of functions is added to the contract's runtime for calling to the external contract's public interface. For now, contract type definitions are only visible to subsequently defined contracts, this can be changed later.
- Calls to external contracts in Fe (e.g. `Foo(foo_address).bar(42, my_string)`) are mapped to calls to the runtime functions mentioned above. So for example, the call mentioned before is mapped to `Foo_bar($foo_address, 42, …
=> Contract type and external calls.

.gitignore, parser/src/tokenizer/tokenize.rs
* Checks for balanced brackets ( { and ] in a parser
* Handle unicode chars as error tokens in the parser
Fixes #226
Fixes #221
=> Fixes unicode and brackets tokens in the parser

analyzer/src/lib.rs, analyzer/src/namespace/scopes.rs
Nothing wrong but a fall out from #203. This adds convenience helper to the contract and module scopes to filter for a list of type defintions.
Basically took some existing code and put it in a function + wrangling 20 minutes about the right syntax for the closure.
=> Add get_type_defs/get_module_type_defs to scope

.github/workflows/main.yml, analyzer/src/lib.rs, analyzer/src/namespace/operations.rs, analyzer/src/namespace/types.rs, analyzer/src/traversal/expressions.rs, analyzer/src/traversal/mod.rs, analyzer/src/traversal/module.rs, analyzer/src/traversal/structs.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/mappers/module.rs, compiler/src/yul/names.rs, compiler/src/yul/operations/mod.rs, compiler/src/yul/operations/structs.rs, compiler/src/yul/runtime/functions/mod.rs, compiler/src/yul/runtime/functions/structs.rs, compiler/src/yul/runtime/mod.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/structs.fe, newsfragments/203.feature.md, parser/src/ast.rs, parser/src/ast_traits.rs, parser/src/parsers.rs, parser/tests/fixtures/parsers/struct_def.ron, parser/tests/test_parsers.rs
Fe should support structs to allow better user defined abstractions.
This PR lays the ground work for struct support as demonstrated with the following test.
```
struct House:
price: u256
size: u256
vacant: bool
contract Foo:
pub def bar() -> u256:
building: House = House(300, 500, true)
assert building.size == 500
assert building.price == 300
assert building.vacant
building.vacant = false
building.price = 1
building.size = 2
assert building.vacant == false
assert building.price == 1
assert building.size == 2
return building.size
```
There are still a few open todos which were moved into dedicated issues (see todos)
=> Add support for structs

analyzer/src/namespace/events.rs, analyzer/src/namespace/scopes.rs, analyzer/src/traversal/assignments.rs, analyzer/src/traversal/contracts.rs, analyzer/src/traversal/declarations.rs, analyzer/src/traversal/expressions.rs, analyzer/src/traversal/functions.rs, analyzer/src/traversal/module.rs, analyzer/src/traversal/structs.rs, compiler/src/abi/builder.rs, compiler/src/abi/utils.rs, compiler/src/errors.rs, compiler/src/evm/mod.rs, compiler/src/lib.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/operations/contracts.rs, compiler/src/yul/operations/data.rs, compiler/src/yul/runtime/abi_dispatcher.rs, compiler/src/yul/runtime/functions/contracts.rs, parser/src/errors.rs, parser/src/parsers.rs, parser/tests/test_parsers.rs
1. We had a mix of using `String` or `&str` for function parameters with no clear guidance on when to use which
2. We were using `String` for function parameters resulting in:
a.) Lots of verbose `to_string()`, `clone()` usage
b.) More memory allocations than necessary
This PR changes the code base to follow a simple rule which may not always result in fewest allocations but has seems to have reduced the overall amount of allocations while at the same time cleaning up a lot of verbosity and being very simple. The rule that was followed is to simple always use `&str` as function parameters and use `to_owned()` wherever we need to convert from a string slice to an allocated `String`.
=> Refactor string usage to be aligned across code base and make fewer allocations

analyzer/src/namespace/types.rs, analyzer/src/traversal/expressions.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/runtime/functions/structs.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/structs.fe, newsfragments/246.feature.md
We did not support updating individual struct fields in storage (e.g. `self.my_struct.some_field = 1`)
1. Make the traversal recognize nested attribute expressions
2. Map them to carry the location of the entire struct
3. Map field of storage struct to a pointer of `ptr_of_storage_struct + 32 * field_index`
4. Add test
=> Support updating struct fields in storage

compiler/src/yul/runtime/abi_dispatcher.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/empty.fe, newsfragments/219.bugfix.md
As identified by the fuzzer in #219 contracts without any public functions compile to faulty YUL.
Compile to `pop(0)` instead of `switch (..)` when there are no public functions.
=> Fix bug where compilation of contracts without public functions would result in malformed YUL

analyzer/src/builtins.rs, analyzer/src/lib.rs, analyzer/src/traversal/expressions.rs, common/src/utils/keccak.rs, compiler/src/yul/mappers/expressions.rs, compiler/tests/compile_errors.rs, compiler/tests/evm_contracts.rs, compiler/tests/evm_runtime.rs, compiler/tests/fixtures/compile_errors/keccak_called_with_wrong_type.fe, compiler/tests/fixtures/keccak.fe, compiler/tests/utils.rs, newsfragments/255.feature.md
As discussed in #188. Fe needs to expose the `keccak256` hash function to be usable from user code.
1. Implemented `keccak256` as a global function
2. Analyzer ensures it can only be called with `bytes[n]` parameter
3. Mapper is pretty straight forward
4. keccak utils were slightly refactored to expose a bare `get_keccak256` method
5. Added contract tests to calculate various keccaks
6. Added test to prove `keccak256` can not be called with arrays of other types
7. Added bare runtime tests for the YUL `keccak256` function
=> Implement keccak256 as builtin method

compiler/tests/evm_contracts.rs, compiler/tests/fixtures/math.fe
We need a Fe implementation of `sqrt` and `min` for the Uniswap demo.
Added a fixture `math.fe` that implements those.
=> Add test that demos sqrt and min function needed for the Uniswap demo

analyzer/src/errors.rs, analyzer/src/traversal/expressions.rs, compiler/tests/compile_errors.rs, compiler/tests/fixtures/compile_errors/struct_call_without_kw_args.fe, compiler/tests/fixtures/structs.fe, newsfragments/260.feature.md
Example:
```
struct House:
vacant: bool
price: u256
```
Currently, `House` can be instantiated as `House(true, 1000000)`.
This means:
1. Property assignment can easily get mixed up leading to bugs
2. struct initialization is visually very close to regular function invocations
With this change it is required to be instantiated like `House(vacant=true, price=1000000)`
While working on this it got me thinking if this is something that should be handled on the parser stage instead but I don't think that would be straight forward because technically there is nothing the syntax is identical with method invocation syntax.
We **could** move this into the parser stage **if** we used a distinct syntax such as `House(vacant: true, price: 100)`. But I'm personally ok to keep it as with the check …
=> Require KWargs for struct initialization

analyzer/src/traversal/functions.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/return_empty_tuple.fe, newsfragments/261.bugfix.md
These two methods should both be treated as returning `()`
```
pub def explicit_return():
return
pub def implicit():
pass
```
Without this change, the `explicit_return` crashes the compiler.
Treat a `None` value in `FuncStmt::Return` as having an expression with an empty tuple.
=> Fix issue where explicit return of implicit empty truple crashes the compiler

analyzer/src/namespace/types.rs, compiler/tests/fixtures/structs.fe
The expanded test was failing with a type error on struct initialization since the values are retrieved in an effectively random order.
Added a vector to keep track of field order.
=> Ordered struct fields.

analyzer/src/traversal/expressions.rs, compiler/src/yul/mappers/expressions.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/return_bool_inverted.fe, newsfragments/264.feature.md
Fe doesn't yet support the boolean `not` operator. E.g. the following code doesn't compile:
```
if not covid_test.is_positive(person):
allow_boarding(person)
```
1. Analyzer validates `UnaryOperator::Not` is used with `bool` only
2. Mapper maps it to `iszero([operand])`
3. Tests
=> Support boolean not operator

analyzer/src/namespace/types.rs, compiler/src/yul/mappers/assignments.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/runtime/functions/math.rs, compiler/src/yul/runtime/functions/mod.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/checked_arithmetic.fe, compiler/tests/utils.rs, newsfragments/265.feature.md
As explained in #153 artihmetic operations should check for under/overflows by default and revert if such are detected.
This adds checks for all additions of both signed and unsigned integers. 
1. Added `checked_add_u256` and `checked_add_i256` functions to runtime
2. Used them for `fe::BinOperator::Add` in mapper
=> Do over/underflow checks for addition (SafeMath)

analyzer/src/builtins.rs, analyzer/src/traversal/expressions.rs, compiler/src/yul/mappers/expressions.rs, compiler/tests/compile_errors.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/compile_errors/non_bool_and.fe, compiler/tests/fixtures/compile_errors/non_bool_or.fe, compiler/tests/fixtures/return_bool_op_and.fe, compiler/tests/fixtures/return_bool_op_or.fe, compiler/tests/fixtures/self_address.fe, newsfragments/270.feature.md, spec/index.md
We didn't support the two small features mentioned above. They are both needed for the Uniswap demo.
- analyzing the expressions
- mapping the expressions
- testing
=> Support for self.address and bool operations

analyzer/src/lib.rs, analyzer/src/traversal/expressions.rs, compiler/src/abi/builder.rs, compiler/src/abi/elements.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/mappers/functions.rs, compiler/tests/fixtures/return_empty_tuple.fe, newsfragments/276.feature.md, parser/src/parsers.rs, parser/tests/fixtures/parsers/func_def.ron, parser/tests/fixtures/parsers/type_desc.ron
Even though functions do always implicitly return empy tuples it isn't yet supported to actually use the empty tuple syntax (`()`) in code.
E.g. the following doesn't work:
```
pub def explicit_return():
return ()
```
This doesn't work either:
```
pub def explicit_return() -> ():
pass
```
With this change, all of these are treated equal:
```
contract Foo:
pub def explicit_return_a1():
return
pub def explicit_return_a2():
return ()
pub def explicit_return_b1() ->():
return
pub def explicit_return_b2() ->():
return ()
pub def implicit_a1():
pass
pub def implicit_a2() ->():
pass
```
1. Taught the Parser how to parse tuples via the `tuple_type` function
2. Added tests for tuple parsing
3. Added support for (empty!) tuples in the analyzer and mapper pass
4. Taught the mapper to treat `return …
=> Full support for empty tuples

README.md
Link in the Readme to the ERC20 implementation does not work
Added the link I believe is the right one: https://github.com/ethereum/fe/blob/master/compiler/tests/fixtures/demos/erc20_token.fe
=> Readme: Fix link to ERC20 implementation

compiler/src/yul/mappers/assignments.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/names.rs, compiler/src/yul/runtime/functions/math.rs, compiler/tests/evm_contracts.rs, compiler/tests/fixtures/checked_arithmetic.fe, newsfragments/271.feature.md
We do not yet perform overflow/underflow checks for multiplications.
Pretty straight forward based on the previous implementations for add and sub. Except for that pesty rusty-evm bug that I created an issue for: https://github.com/ethereum/fe/issues/285
=> Add overflow/underflow checks for multiplicatons

compiler/src/yul/runtime/functions/abi.rs, compiler/src/yul/runtime/functions/contracts.rs, compiler/src/yul/runtime/functions/data.rs, compiler/src/yul/runtime/functions/mod.rs
Runtime functions of the `yul` module needed to be exposed individually, making it cumbersome to expose them all at ones, especially given that the runtime API might grow in the future
This commit moves yul runtime functions of various modules into dedicated `*::all()` APIs to make exposing them easier.
Closes #269
=> Reorganize runtime functions

analyzer/src/namespace/events.rs, analyzer/src/namespace/scopes.rs, analyzer/src/namespace/types.rs, compiler/src/yul/operations/abi.rs, compiler/src/yul/operations/structs.rs, compiler/src/yul/runtime/functions/structs.rs, compiler/tests/runtime.rs
The only way to get a `FixedSize::Base(Base::Bool)` variant is to use that very API. 
As mentioned in #274, a constructor API like `FixedSize::bool()` makes this easier.
To improve developer ergonomics, this commit introduces a new API
```
FixedSize::bool()
```
which is equivalent to:
```
FixedSize::Base(Base::Bool)
```
Closes #274
=> Introduce new FixedSize::bool() API in fe::analyzer

analyzer/src/lib.rs, analyzer/src/namespace/scopes.rs, analyzer/src/traversal/assignments.rs, analyzer/src/traversal/contracts.rs, analyzer/src/traversal/declarations.rs, analyzer/src/traversal/expressions.rs, analyzer/src/traversal/functions.rs, analyzer/src/traversal/module.rs, compiler/tests/fixtures/demos/uniswap.fe, compiler/tests/fixtures/features/two_contracts.fe, newsfragments/298.feature.md
This superseded #294 
If two contracts are defined in a module, only the second contract can see the interface of the first.
e.g.
```python
contract Foo:
...
contract Bar:
...
```
1. Contract analysis is split into multiple passes:
1 The first pass collects contracts with their function definition but does not inspect function bodies and contract fields
2. Once every contract was analyzed, we analyze the function bodies and contract field of each contract in a subsequent pass
2. Because the module scope now contains all contracts it needs a way to filter out the main contract when it is aggregating `external_contracts`. To do that, `name` was added to `ContractScope` (we also have `name` for `BlockScope` so there's a precedence for having the `name` as a scope identifier) so that we can …
=> Improve visibility of subsequently defined contracts

analyzer/src/lib.rs, analyzer/src/namespace/events.rs, analyzer/src/namespace/scopes.rs, analyzer/src/namespace/types.rs, analyzer/src/traversal/contracts.rs, analyzer/src/traversal/expressions.rs, analyzer/src/traversal/functions.rs, compiler/src/abi/builder.rs, compiler/src/abi/elements.rs, compiler/src/abi/mod.rs, compiler/src/lib.rs, compiler/src/yul/mappers/contracts.rs, compiler/src/yul/mod.rs, compiler/src/yul/operations/data.rs, compiler/src/yul/runtime/abi_dispatcher.rs, compiler/src/yul/runtime/functions/contracts.rs, compiler/src/yul/runtime/mod.rs, compiler/tests/demo_uniswap.rs, compiler/tests/fixtures/demos/uniswap.fe, compiler/tests/fixtures/stress/abi_encoding_stress.fe, compiler/tests/stress.rs, compiler/tests/utils.rs, docs/build.md, newsfragments/296.feature.md
fixes #282 
Structs were not being added to the ABI. For example, we could not build the JSON ABI for the following example:
```
struct MyStruct:
num1: u256
num2: u256
contract MyContract:
pub def foo(my_struct: MyStruct) -> MyStruct:
return my_struct
```
- Added `components` to the `AbiEncoding` trait.
- Added field names to function and event attributes.
- Updated the ABI builder to use information from the analyzer.
=> Structs in the ABI

compiler/src/yul/mappers/contracts.rs, compiler/tests/features.rs, compiler/tests/fixtures/demos/uniswap.fe, compiler/tests/fixtures/features/create_contract.fe, compiler/tests/fixtures/features/create_contract_from_init.fe, newsfragments/304.bugfix.md
fixes #284
Added the `created_contracts` vector to the constructor object.
---
The Yul optimizer does not currently remove these objects if they are unused. Meaning, created contracts will be included in the initialization code twice no matter what. This does not increase the contract size, but increases the initialization code size.
The cost of this extra tx data is 16 for non-zero bytes and 4 for zero bytes (see [appendix g](https://ethereum.github.io/yellowpaper/paper.pdf)).
For example, say we write a contract that deploys an ERC-20 contract and has an `__init__` that does **not** create an ERC-20 contract. A compiled Fe ERC-20 contract is about `2600` bytes. So, the extra cost would be slightly less than `42000`, which is roughly equivalent to the cost of 2 `sstore` operations. This …
=> Created contracts included in constructor object.

compiler/src/yul/mappers/assignments.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/names.rs, compiler/src/yul/runtime/functions/math.rs, compiler/tests/features.rs, compiler/tests/fixtures/features/checked_arithmetic.fe, newsfragments/308.feature.md
Integer division operations are currently unchecked which can lead fatal errors.
Pretty straight forward like the previous checks for other arithmetic operations.
=> Add checks for integer division

analyzer/src/errors.rs, analyzer/src/namespace/types.rs, analyzer/src/traversal/expressions.rs, compiler/src/yul/mappers/assignments.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/names.rs, compiler/src/yul/runtime/functions/math.rs, compiler/tests/compile_errors.rs, compiler/tests/features.rs, compiler/tests/fixtures/compile_errors/pow_with_signed_exponent.fe, compiler/tests/fixtures/compile_errors/pow_with_wrong_capacity.fe, compiler/tests/fixtures/features/checked_arithmetic.fe, compiler/tests/fixtures/features/return_pow_i256.fe, compiler/tests/runtime.rs, newsfragments/313.feature.md
We need to perform over/underflow checks for exponentiation maths.
Pretty much like with the other operations except that for exponentiation we can not support that the exponent is signed. To still allow calculations such as `-2 ** 3` we allow the right hand side to be unsigned as long as it size is the equal or smaller than the left hand side. The resulting expression gets the type of the left hand side which is also what will be used for the under/overflow checks.
=> Checked pow

analyzer/src/traversal/functions.rs, compiler/tests/compile_errors.rs, compiler/tests/fixtures/compile_errors/return_from_init.fe, newsfragments/323.bugfix.md, newsfragments/README.md
fixes #307.
Semantic checks missed `__init__` return type.
Assert the return type is `()`.
=> Fix ICE when '__init__' returns any other type than '()'

Makefile
Coverage was getting flaky because the Uniswap tests take a while to run.
Increased timeout from one to two minutes
=> Increase coverage timeout

analyzer/src/namespace/types.rs, compiler/tests/compile_errors.rs, compiler/tests/fixtures/compile_errors/numeric_capacity_mismatch/octal_number.fe, newsfragments/222.bugfix.md
Currently, the analyzer doesn't consider number literals that start with `0`. This leads to ICE in the `yul` mapping pass.
fixes #222 
Reject a number literal if it starts with `0` and has more than two digits.
I also found that lexer doesn't tokenize correctly if number literals start with `0` followed by non zero value.
For example, `02` is tokenized into 
```
[
Token {
typ: NUMBER,
string: "0",
span: Span {
start: 0,
end: 1,
},
line: "02\n",
},
Token {
typ: NUMBER,
string: "2",
span: Span {
start: 1,
end: 2,
},
line: "02\n",
},
Token {
typ: NEWLINE,
string: "\n",
span: Span {
start: 2,
end: 3,
},
line: "02\n",
},
Token {
typ: ENDMARKER,
string: "",
span: Span {
start: 3,
end: 3,
},
line: "",
},
],
```
I'll open an issue for this and …
=> Properly reject octal number literals

analyzer/src/errors.rs, analyzer/src/traversal/functions.rs, compiler/tests/compile_errors.rs, compiler/tests/fixtures/compile_errors/emit_undefined_event.fe, compiler/tests/fixtures/compile_errors/emit_without_call.fe, newsfragments/212.bugfix.md, newsfragments/250.bugfix.md
Currently we do not reject code that uses `emit` with some undefined event such as `emit DoesNotExist`
Fixes #250
1. Introduced a new error type `MissingEventDefinition`
2. Return `Err(SemanticError::missing_event_definition())` when the emitted event does not exit
3. Added a test case
=> Properly reject emitting undefined events

Cargo.lock, compiler/Cargo.toml, compiler/src/errors.rs, compiler/src/lib.rs, compiler/src/yul/mappers/assignments.rs, compiler/src/yul/mappers/contracts.rs, compiler/src/yul/mappers/declarations.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/mappers/functions.rs, compiler/src/yul/mappers/module.rs, compiler/src/yul/mod.rs, compiler/src/yul/operations/abi.rs, compiler/src/yul/runtime/functions/contracts.rs, newsfragments/327.internal.md, src/main.rs
A yul mapping failure is indicative of a bug in the compiler, but the yul mappers were returning Result types. Fixes #168.
Yul mappers now all panic on failure. I also added a panic hook to log the following message when fe panics:
```
You've hit an internal compiler error. This is a bug in the Fe compiler.
Fe is still under heavy development, and isn't yet ready for production use.
If you would, please report this bug at the following URL:
https://github.com/ethereum/fe/issues/new
```
=> Panic when Yul mapping fails; print friendly message when fe panics

analyzer/src/namespace/types.rs, analyzer/src/traversal/contracts.rs, analyzer/src/traversal/declarations.rs, analyzer/src/traversal/expressions.rs, analyzer/src/traversal/functions.rs, analyzer/src/traversal/module.rs, analyzer/src/traversal/structs.rs, analyzer/src/traversal/utils.rs, compiler/src/abi/builder.rs, compiler/src/lowering/mod.rs, compiler/src/types.rs, compiler/src/yul/mappers/contracts.rs, compiler/src/yul/mappers/declarations.rs, compiler/src/yul/mappers/expressions.rs, compiler/src/yul/mappers/functions.rs, compiler/src/yul/mappers/module.rs, compiler/src/yul/utils.rs, newsfragments/332.internal.md, parser/src/ast.rs, parser/src/ast_traits.rs, parser/src/builders.rs, parser/src/parsers.rs, parser/src/tokenizer/types.rs
Before, the AST used slices that point to parts of the source string. This is not compatible with the lowering pass, since we will be adding nodes to the AST.
part of #306 
Refactored the AST to use `String`s instead of `&str`s.
=> Give the AST ownership of its strings.

analyzer/src/traversal/functions.rs, compiler/tests/compile_errors.rs, compiler/tests/fixtures/compile_errors/assert_reason_not_string.fe, newsfragments/335.bugfix.md
We do currently not enforce that assert reasons are of type string.
- added type check
- added test
=> Reject non-string assert reasons with TypeError

analyzer/src/traversal/functions.rs, compiler/tests/compile_errors.rs, compiler/tests/fixtures/compile_errors/emit_with_invalid_call.fe, newsfragments/211.bugfix.md
We currently crash on code such as `emit foo()()` which is mostly due because we don't properly reject it in the parser stage (See https://github.com/ethereum/fe/issues/337)
Fixed it with an extra check in the analyzer pass and filed #337 because the parser is currently getting rewritten.
=> Reject invalid emit

.github/install_deps.sh, .github/workflows/main.yml
CI is borked
1. A bit of cleanup, moving the repeated installation steps into a single script
2. `g++-8` appears to not be available in `ubuntu-latest` but that's ok, changed to `g++-10` instead
3. Temporary fixing rust nightly to a nightly from mid-march as it appears the current nightly errors which might be temporary or means we will need to cut a new `solc-rust` and/or `yultsur` release with updated dependencies
4. Created an issue to unpin the nightly in the future when the issues are resolved: https://github.com/ethereum/fe/issues/357
5. Sneaked in a minor CI perf improvement by removing an unnecessary build step from the linting job
=> Update g++ in CI system dependencies

README.md
Need to replace gitter link with discord
Replaced it
=> Replace gitter with discord invite link

compiler/src/yul/mappers/functions.rs, compiler/src/yul/runtime/functions/data.rs, compiler/tests/features.rs, compiler/tests/fixtures/features/assert.fe, compiler/tests/fixtures/solidity/revert_test.sol, compiler/tests/runtime.rs, compiler/tests/solidity.rs, compiler/tests/utils.rs, newsfragments/288.feature.md, newsfragments/342.internal.md
As described in #288 we do currently not support revert reason strings in `assert` statements.
1. Added a bit machinery to test solidity fixtures and added a new category of tests for such cases
2. Added tests to prove how solidity handles revert reason strings
3. Added a new runtime function `revert_with_reason_string` which follows the error encoding that solidity uses: https://docs.soliditylang.org/en/latest/control-structures.html#revert
3. Added tests for this new runtime method and as a byproduct refactored some helpers to allow detailed testing of reverts as well as setting up a runtime that exposes static strings
4. Hooked up the mapping of `assert` to use the new runtime method when a string reason is given
5. Added several test cases to prove the functionality of assert strings …
=> Proper Revert reasons

compiler/tests/runtime.rs, compiler/tests/utils.rs
Nothing wrong, continued what was proposed here: https://github.com/ethereum/fe/pull/342#discussion_r616551951
Basically, this gets rid of `test_runtime_functions` and `test_runtime_functions_revert` and instead adds an `execute` method to the `Runtime` which returns an `ExecutionOutput` that supports running various expectations.
=> Refactoring of runtime testing helpers

analyzer/src/errors.rs, analyzer/src/traversal/expressions.rs, compiler/tests/compile_errors.rs, compiler/tests/fixtures/compile_errors/circular_dependency_create.fe, compiler/tests/fixtures/compile_errors/circular_dependency_create2.fe, newsfragments/362.bugfix.md
As found by the fuzzer in #362, circular dependencies when using `create` or `create2` were not correctly rejected yet.
In the analyzer we check if the name of the contract to create is the same as the contract of the inherited scope. If so, we reject it with a newly added `CircularDependency` kind.
=> Properly reject circular dependency when using create/create2

analyzer/src/errors.rs, analyzer/src/traversal/functions.rs, compiler/src/lowering/mappers/expressions.rs, compiler/src/lowering/mappers/functions.rs, compiler/src/yul/mappers/functions.rs, compiler/tests/compile_errors.rs, compiler/tests/fixtures/compile_errors/emit_with_invalid_call.fe, compiler/tests/fixtures/compile_errors/emit_without_call.fe, parser/src/ast.rs, parser/src/grammar/expressions.rs, parser/src/grammar/functions.rs, parser/tests/fixtures/parsers/emit_stmt.ron, parser/tests/fixtures/parsers/guest_book.ron, parser/tests/fixtures/parsers/small_stmt.ron
As explained in #337 our current AST allows any expression to follow the `emit` keyword and the analyzer ensures
that what follows actually is an event call. Clearly the analyzer is currently handling something that should rather be rejected at the parsing stage.
1. The `emit` AST was changed to not take a `value` of `Expr` but rather a `name` of `String` and as well as a list of `CallArg`.
2. Parser, analyzer and lowering were changed accordingly
3. The analyzer error `EventInvocationExpected` was removed
- We should have parser tests for this but they are out of scope for this PR
=> Tighten AST for emit statements

analyzer/src/traversal/expressions.rs, compiler/src/lowering/mappers/expressions.rs, compiler/src/yul/mappers/expressions.rs, parser/src/ast.rs, parser/src/grammar/Fe.grammar, parser/src/lexer/token.rs
As mentioned in #279 we do have some stub code for the Ellipsis `...` syntax which we carried over from our Python heritage but don't actually plan to support.
Removed all affected code
=> Remove stub support for Ellipsis

docs/release_notes.md, newsfragments/4711.internal.md, newsfragments/validate_files.py
Thanks for cutting the release yesterday @g-r-a-n-t. It also has exposed a small manual chore that I used to do these past releases. Basically, whenever we end a news fragment with a code block example it breaks the formatting with the issue link if there's not a new line after the code block.
I have fixed the formatting in the release notes (and on the release page) and added a check to our CI to simply always require us to end news fragment files with a new line.
=> Fixup formatting in release notes and tighten CI checks to prevent such in the future

analyzer/src/traversal/expressions.rs, compiler/tests/cases/compile_errors.rs, compiler/tests/cases/lowering/mod.rs, compiler/tests/fixtures/compile_errors/bad_tuple_attr1.fe, compiler/tests/fixtures/compile_errors/bad_tuple_attr2.fe, newsfragments/401.bugfix.md
closes #396 and closes #399
We weren't verifying that tuple attributes started with "item", which resulted in undefined attributes such as `iteo0` making it to the post-lowering analysis stage.
=> Validate that tuple attributes are prefixed with 'item'

Makefile, analyzer/tests/fixtures/demos/guest_book.fe, analyzer/tests/snapshots/analysis__case_002_guest_book.snap, docs/src/quickstart/first_contract.md, docs/src/quickstart/index.md, docs/src/quickstart/installation.md, docs/src/spec/index.md, newsfragments/403.doc.md, website/index.html
A small collection of things around the website:
- The download button is linking to the release page introducing an extra barrier before the actual file
- We have some stubs in our Fe guide such as the Quickstart that needs to be filled in.
- The guestbook example could be slightly improved
1. The buttons now link to the actual binary. To do that the build pipeline reads the current compiler version and replaces a marker in the website. The website shows the correct button according to the users OS *unless* if we don't support the OS in which case we will link to the release page so that the user can see what kind of OS are supported.
2. The guestbook example makes the `map` private and renames it to be not repeat the contract name
3. Created Quickstart with Installation & First contract …
=> Fill in Quickstart in Fe guide

Cargo.lock, analyzer/Cargo.toml, analyzer/src/namespace/types.rs, analyzer/src/traversal/expressions.rs, common/Cargo.toml, common/src/lib.rs, common/src/numeric.rs, compiler/Cargo.toml, compiler/src/yul/mappers/expressions.rs, compiler/tests/cases/compile_errors.rs, compiler/tests/cases/features.rs, compiler/tests/fixtures/compile_errors/numeric_capacity_mismatch/octal_number.fe, compiler/tests/fixtures/features/radix_binary.fe, compiler/tests/fixtures/features/radix_hex.fe, compiler/tests/fixtures/features/radix_octal.fe, newsfragments/333.feature.md, parser/src/grammar/expressions.rs, parser/src/lexer/token.rs
closes #333 
1. Added `common::numeric::Literal` to abstract string represented numeric literals.
2. Consistently use `BigInt` for semantic analysis, this approach is the same as `rustc` does (it holds `u128` for numeric integers).
2. Removed `lexical_core` because it doesn't provide `from_str_radix` like methods. And also, I think we don't need to check the details of `IntErrorKind` in almost all cases. This is because, looking at the definition of [`IntErrorKind`](https://doc.rust-lang.org/std/num/enum.IntErrorKind.html) in detail, `IntErrorKind::Empty` is the only error kind that we have to consider it an internal compiler error.
We may need to reconsider the usage of `BigInt`, I think it would be better to use [`U256`](https://docs.rs/primitive-types/0.9.0/primitive_types/struct.U256.h …
=> Allow hex/octal/binary radix numeric literals

.github/workflows/main.yml, Makefile, analyzer/tests/analysis.rs, compiler/src/abi/builder.rs, compiler/src/yul/names.rs, compiler/tests/cases/compile_errors.rs, compiler/tests/cases/demo_uniswap.rs, compiler/tests/cases/lowering/mod.rs, compiler/tests/cases/utils.rs, parser/tests/cases/parse_ast.rs
Some files are not checked by `clippy` due to the missing `--workspace` option.
=> Missing `--workspace` option of `clippy`

analyzer/src/traversal/expressions.rs, compiler/src/yul/operations/abi.rs, compiler/src/yul/runtime/functions/contracts.rs, compiler/tests/cases/stress.rs, compiler/tests/fixtures/stress/external_calls.fe, newsfragments/415.feature.md
closes #405 
closes #400 
closes #321 
I also noticed that there was a bug preventing us from calling functions on `contract` fields (e.g. `self.my_contract`).
Used `returndatasize` and `returndatacopy` to deal with sizes that aren't known at compile-time (it's now much simpler).
See the note at the bottom of this [section](https://docs.soliditylang.org/en/v0.8.4/yul.html#evm-dialect):
> The call* instructions use the out and outsize parameters to define an area in memory where the return or failure data is placed. This area is written to depending on how many bytes the called contract returns. If it returns more data, only the first outsize bytes are written. You can access the rest of the data using the returndatacopy opcode. If it returns less data, then the remaining bytes are not …
=> Dynamically sized return support for external calls

Cargo.lock
Fe build broke on my machine after updating to gcc 11 (specifically solc compilation). There was a recent commit in the solidity repo to fix the compiler errors. This PR bumps the version of solc-rust.
=> Updated solc.

Cargo.lock, analyzer/Cargo.toml, analyzer/src/traversal/module.rs, compiler/src/lowering/mappers/module.rs, compiler/src/yul/mappers/module.rs, docs/src/spec/index.md, newsfragments/361.feature.md, parser/Cargo.toml, parser/src/ast.rs, parser/src/grammar/module.rs, parser/src/lexer/token.rs, parser/src/parser.rs, parser/tests/cases/errors.rs, parser/tests/cases/parse_ast.rs, parser/tests/cases/snapshots/cases__errors__contract_invalid_version_requirement.snap, parser/tests/cases/snapshots/cases__errors__contract_missing_version_requirement.snap, parser/tests/cases/snapshots/cases__parse_ast__module_stmts.snap, parser/tests/cases/snapshots/cases__parse_ast__pragma1.snap, parser/tests/cases/snapshots/cases__parse_ast__pragma2.snap, parser/tests/cases/snapshots/cases__parse_ast__pragma3.snap, tests/fixtures/compile_errors/invalid_compiler_version.fe, tests/src/compile_errors.rs, tests/src/snapshots/fe_compiler_tests__compile_errors__invalid_compiler_version.snap
As described in #361 developers need to have a way to express that a piece of code can only be compiled with a compiler where the version matches a given requirement.
- Added support for `pragma` keyword in the parser
- Version requirement is parsed using the `semver` crate
- The Analyzer checks the compiler version against the version requirement and raises a `WrongCompilerError` if needed.
=> Add support for pragma statement

.github/workflows/main.yml, Cargo.lock, Cargo.toml, fuzz/Cargo.toml, parser/Cargo.toml, parser/tests/cases/errors.rs, parser/tests/cases/parse_ast.rs, test-utils/Cargo.toml, tests/Cargo.toml, tests/src/compile_errors.rs
Tests don't run on wasm.
Fixed the wasm32-unknown-unknown build (with solc-backend feature disabled), uncommented the wasm test config from the github workflow, and made some of the tests wasm-friendly.
I've only wasmified the tests that don't require solc, do use insta, and don't use rstest. So, the parser tests and the analyzer error tests. The other non-solc tests need to be refactored a bit to work on wasm, which I'd prefer to do as part of a future test cleanup pr.
=> Re-enable wasm tests

analyzer/src/traversal/functions.rs, newsfragments/435.feature.md, tests/fixtures/compile_errors/non_pub_init.fe, tests/fixtures/features/ownable.fe, tests/src/compile_errors.rs, tests/src/snapshots/fe_compiler_tests__analysis__case_030_ownable.snap, tests/src/snapshots/fe_compiler_tests__compile_errors__non_pub_init.snap
closes #353
See https://github.com/ethereum/fe/issues/353#issuecomment-848205436
Throw a compiler error if `__init__` is not public.
My thinking is that `__init__` should either always be *public* or *not public*. If there are good reasons to go with always not pub, then I can modify this PR to do the opposite.
=> `__init__` must be `pub`

analyzer/src/context.rs, analyzer/src/traversal/declarations.rs, compiler/src/lib.rs, compiler/src/lowering/mappers/contracts.rs, compiler/src/lowering/mappers/expressions.rs, compiler/src/lowering/mappers/functions.rs, compiler/src/lowering/mappers/module.rs, compiler/src/lowering/mappers/types.rs, compiler/src/lowering/mod.rs, compiler/tests/cases/lowering/mod.rs, newsfragments/376.feature.md, tests/fixtures/features/tuple_destructuring.fe, tests/src/features.rs
Fixes #376 
As suggested in #376, implement tuple restructuring in the lowering pass.
e.g.
```
(x, y): (u256, bool) = (42, true)
```
is basically lowered to 
```
tmp_tuple: (u256, bool) = (42, true)
x: u256 = tmp_tuple.item0
y: bool = tmp_tuple.item1
```
The problem here is the possibility of name conflict of `tmp_tuple`, so we need to make a unique name for `tmp_tuple`. This is the same problem described in #377.
I tried to resolve the problem by prepending `$` which is a legal character in `yul` but illegal in `Fe`, and appending a fresh number to the name to avoid name conflict with another lowered variable. As a result, `tmp_tuple` above will be lowered to `$tmp_tuple_0` .
Rewrite lowering test if the above solution for name conflict is approved.
[//]: # (Stay ahead of things, add …
=> Implement tuple destructuring 

docs/src/SUMMARY.md, docs/src/quickstart/deploy_contract.md, docs/src/quickstart/first_contract.md, docs/src/quickstart/index.md, docs/src/spec/index.md, website/index.html
We need a tutorial that shows how to deploy Fe code and interact with it.
Added a tutorial that takes the guest book, deploys it on Görli and interacts with it.
I want to expand with an additional section that explains how to get the code (and ABI) verified but that's currently blocked by #424. I'm waiting on Etherscan to get back with an response.
=> Add tutorial that deploys and uses Guestbook on Görli

.github/install_deps.sh
CI is currently broken.
Turns out our system dependencies install script was missing an `apt-get update` which started causing problems with the boost install not getting carried out as entirely causing the build to fail). Adding `apt-get update` was all it needed to fix it.
=> Fix broken CI build

analyzer/src/namespace/types.rs, analyzer/src/traversal/expressions.rs, newsfragments/444.bugfix.md, newsfragments/445.bugfix.md, tests/fixtures/compile_errors/invalid_string_field.fe, tests/src/compile_errors.rs, tests/src/snapshots/fe_compiler_tests__compile_errors__array_mixed_types.snap, tests/src/snapshots/fe_compiler_tests__compile_errors__call_event_with_wrong_types.snap, tests/src/snapshots/fe_compiler_tests__compile_errors__external_call_type_error.snap, tests/src/snapshots/fe_compiler_tests__compile_errors__invalid_string_field.snap
As found by the fuzzer, the following code does currently result in a panic.
```
contract Foo:
pub def foo():
"".does_not_exist
````
1. Return proper user error
2. Ensure `String<N>` type is capitalized when displayed to the user
=> Fix ICE when accessing an invalid attribute on a type

analyzer/src/traversal/expressions.rs
There were a few places where we returned a `FatalError` even though the return type was known. Doing so prevents us from collecting more errors without the need to do so.
Removed the `FatalError`s
=> Remove some fatal errors

analyzer/src/traversal/functions.rs, tests/fixtures/compile_errors/issue_451.fe, tests/src/compile_errors.rs, tests/src/snapshots/fe_compiler_tests__compile_errors__issue_451.snap
#451 demonstrates an interesting issue where we crash when trying to present a certain error. The reason for that is that the function is defined multiple times and when we retrieve the type information for another error we don't get the type for that function `bar` that we assume but for that other `function` bar that has a different type.
An easy way to fix this is to say that duplicate definitions are treated as fatal errors with the reasoning that it becomes unsafe to retrieve type information for definitions of which we have multiple for the same name.
=> Make duplicate function definitons a fatal error

Cargo.lock, compiler/Cargo.toml, fuzz/Cargo.toml, test-utils/Cargo.toml, test-utils/src/lib.rs, tests/Cargo.toml, tests/src/demo_guestbook.rs, tests/src/demo_uniswap.rs, tests/src/features.rs
Our `ethereum_types`, `primitive_types` and `evm_runtime` dependencies were out of date. We also had one test disabled that was waiting on these upgrades
- Modifications on some testing helpers (done by Grant)
- Re-enabled arithmetic test that was failing with previous eth_runtime versions
=> Upgrade some dependencies and re-enable test

Makefile
A tiny breakage that came out of the big repository reorganization. The website needs to read the current Fe version but the `cargo pkgid` command was confused now that the layout has changed.
Added a `cd crates/fe` to the command. I tried specifying the command via `cargo pkgid -p crates/fe` but it seems that command only takes absolute file paths so I went for the `cd` instead.
=> Fix path issue with cargp pkgid command

README.md
The hyperlink in [README.md](https://github.com/ethereum/fe/blob/master/README.md) that directs the user to the fe contract examples is not updated.
I replaced the old hyperlink with the updated hyperlink.
=> Update readme hyperlink

docs/src/quickstart/first_contract.md
string100 instead of String<100>
error message was outdated as well
changed to String<100>
updated error message as well
=> Update file because of updated Syntax

crates/analyzer/tests/snapshots/analysis__strings.snap, crates/test-files/fixtures/features/strings.fe, crates/tests/src/features.rs, crates/yulgen/src/lib.rs, newsfragments/448.bugfix.md
As found by the fuzzer in #448, static strings do not work yet if they contain line breaks.
Added the proper escaping for data objects when converting from ` yul::Object` to the JSON string that is passed to `solc`.
=> Fix issue with multi line strings in Fe code

crates/analyzer/src/namespace/scopes.rs, crates/analyzer/src/operations.rs, crates/analyzer/src/traversal/contracts.rs, crates/analyzer/src/traversal/declarations.rs, crates/analyzer/src/traversal/expressions.rs, crates/analyzer/src/traversal/functions.rs, crates/analyzer/src/traversal/module.rs, crates/analyzer/src/traversal/types.rs, crates/common/src/diagnostics.rs, crates/common/src/files.rs, crates/common/src/numeric.rs, crates/fe/src/main.rs, crates/lowering/src/mappers/module.rs, crates/lowering/tests/lowering.rs, crates/test-utils/src/lib.rs, crates/tests/src/features.rs, crates/tests/src/solidity.rs, crates/tests/src/stress.rs, crates/yulc/src/lib.rs, crates/yulgen/src/mappers/declarations.rs, crates/yulgen/src/mappers/expressions.rs, crates/yulgen/src/mappers/functions.rs, crates/yulgen/src/operations/abi.rs, crates/yulgen/src/runtime/functions/abi.rs, crates/yulgen/src/runtime/functions/structs.rs
clippy update
ran `clippy --fix`
=> fixed build

crates/analyzer/src/traversal/expressions.rs, crates/analyzer/src/traversal/functions.rs, crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/analysis__assert.snap, crates/analyzer/tests/snapshots/analysis__revert.snap, crates/analyzer/tests/snapshots/analysis__structs.snap, crates/analyzer/tests/snapshots/errors__assert_sto_msg_no_copy.snap, crates/analyzer/tests/snapshots/errors__for_loop_sto_iter_no_copy.snap, crates/analyzer/tests/snapshots/errors__revert_sto_error_no_copy.snap, crates/test-files/fixtures/compile_errors/assert_sto_msg_no_copy.fe, crates/test-files/fixtures/compile_errors/for_loop_sto_iter_no_copy.fe, crates/test-files/fixtures/compile_errors/revert_sto_error_no_copy.fe, crates/test-files/fixtures/features/assert.fe, crates/test-files/fixtures/features/for_loop_with_static_array_from_sto.fe, crates/test-files/fixtures/features/if_statement_test_from_sto.fe, crates/test-files/fixtures/features/return_sum_list_expression_1.fe, crates/test-files/fixtures/features/revert.fe, crates/test-files/fixtures/features/while_loop_test_from_sto.fe, crates/tests/src/features.rs, newsfragments/493.bugfix.md
closes #491 
Searched usages of `expression::expr` and fixed places where `value_expr` or `assignable_expr` needed to be used.
=> Using `value_expr` and `assignable_expr` analysis functions where appropriate.

crates/analyzer/src/traversal/functions.rs, crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/errors__missing_return_after_if.snap, crates/test-files/fixtures/compile_errors/missing_return_after_if.fe, crates/test-files/src/lib.rs, newsfragments/497.bugfix.md
As described in #497 the following code does compile in master but should generate a user error instead. It needs to error because the code is missing a return statement since it is not guaranteed that the execution follows the arm of the `if` statement.
```
contract Foo:
pub def bar(val: u256) -> u256:
if val > 1:
return 5
```
The check in `all_paths_return_or_revert` is wrong because it counts a missing `else` branch as if the code returns when clearly a missing `else` branch shouldn't indicate such thing.
=> Reject certain code that should return but doesn't

crates/parser/src/grammar/contracts.rs, crates/parser/src/grammar/functions.rs, crates/parser/src/grammar/module.rs, crates/parser/src/grammar/types.rs, crates/parser/src/parser.rs, crates/parser/tests/cases/errors.rs, crates/parser/tests/cases/snapshots/cases__errors__fn_def_kw.snap
The error message for "def foo():" assumes that the user is trying to define a field called "def", so it's not as helpful as it could be.
Added a note about the `fn` keyword.
```
error: failed to parse field definition
┌─ fn_def_kw:2:10
│
2 │  pub def f(x: u8):
│          ^ Unexpected token. Expected `:`
│
= Hint: use `fn` to define a function
= Example: `pub fn f( ...`
= Note: field name must be followed by a colon and a type description
= Example: pub def: address
```
We could probably delete this someday, but it's nice for the compiler to alert people to a keyword change.
=> Friendlier parser error for old `def` keyword

crates/analyzer/src/traversal/expressions.rs, crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/analysis__tuple_stress.snap, crates/analyzer/tests/snapshots/errors__bad_tuple_attr3.snap, crates/test-files/fixtures/compile_errors/bad_tuple_attr3.fe, crates/test-files/fixtures/stress/tuple_stress.fe, newsfragments/510.bugfix.md
issue #470  
Leading zeros in tuple indexes should not be allowed.
Check for leading zeros in tuple indexes (like item00 or item001). Small change in expressions.rs + tests.
=> Tuple item leading zeroes #470

crates/analyzer/src/traversal/call_args.rs, crates/analyzer/src/traversal/expressions.rs, crates/analyzer/src/traversal/functions.rs, crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/errors__mislabeled_call_args.snap, crates/analyzer/tests/snapshots/errors__mislabeled_call_args_external_contract_call.snap, crates/test-files/fixtures/compile_errors/mislabeled_call_args.fe, crates/test-files/fixtures/compile_errors/mislabeled_call_args_external_contract_call.fe, newsfragments/517.bugfix.md
As explained in #517, function calls on `self` or external contracts do not check the labels, allowing developers to apply any kind of label and in the worst case leave the user with the impression that they could use labels to call functions with the arguments ordered as they wish (which isn't the case).
Added checks in the analyzer and added tests.
=> Check labels in function calls on self and external contracts

crates/driver/src/lib.rs, newsfragments/535.bugfix.md
closes #523 
Non-fatal parser errors were being ignored when the analysis stage succeeded. I assume this was my fault again (#402 :disappointed:). We probably need tests for the driver crate.
In the simplest way possible. I've done nothing to ensure that something similar won't happen again in the future.
=> Don't ignore non-fatal parser errors when analysis succeeds

crates/analyzer/src/context.rs, crates/analyzer/src/db/queries/events.rs, crates/analyzer/src/db/queries/functions.rs, crates/analyzer/src/db/queries/module.rs, crates/analyzer/src/db/queries/structs.rs, crates/analyzer/src/db/queries/types.rs, crates/analyzer/src/errors.rs, crates/analyzer/src/traversal/assignments.rs, crates/analyzer/src/traversal/call_args.rs, crates/analyzer/src/traversal/declarations.rs, crates/analyzer/src/traversal/expressions.rs, crates/analyzer/src/traversal/functions.rs, crates/analyzer/src/traversal/types.rs, crates/analyzer/src/traversal/utils.rs, crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/errors__invalid_generic_string.snap, crates/analyzer/tests/snapshots/errors__return_type_not_fixedsize.snap, crates/analyzer/tests/snapshots/errors__return_type_undefined.snap, crates/analyzer/tests/snapshots/errors__string_constructor_bad_type_arg.snap, crates/analyzer/tests/snapshots/errors__undefined_type_param.snap, crates/test-files/fixtures/compile_errors/invalid_generic_string.fe, crates/test-files/fixtures/compile_errors/return_type_not_fixedsize.fe, crates/test-files/fixtures/compile_errors/return_type_undefined.fe, crates/test-files/fixtures/compile_errors/string_constructor_bad_type_arg.fe, crates/test-files/fixtures/compile_errors/undefined_type_param.fe, newsfragments/534.bugfix.md
closes #532 -  Here we weren't emitting an error message if the `String` type constructor was ill-formed. Eg `String<x>("hi")` would be rejected without an error message.
closes #530 - Here we were panicking because the fn body diagnostic vec was empty, even though the analysis failed. We shouldn't panic in this case, because an undefined type diagnostic was produced elsewhere (during the analysis of the function signature).
These cases are just symptoms of a problem in the analyzer; we require that a friendly diagnostic be emitted before returning FatalError or TypeError, but can't effectively ensure that that's happening.
FatalError and TypeError now can't be created unless you have a voucher proving that you've emitted a diagnostic. You can receive such a voucher by calling an …
=> Fix "analysis failed but no diagnostics were emitted" panics

README.md
The articulation of the overview heading was wobbly. Not reflecting precision and grace. 'and' was used twice in succession 'python and rust and' , making it awkward. 
I rephrased while keeping the meaning precisely the same, and avoiding incorrect articulation methods. Minimal tweaking for a far better impact. Read it and see for yourself :)
=> Improved articulation of #overview

Cargo.lock, crates/analyzer/tests/snapshots/analysis__erc20_token.snap, crates/parser/Cargo.toml, crates/parser/src/ast.rs, crates/parser/tests/cases/main.rs, crates/parser/tests/cases/print_ast.rs, crates/test-files/fixtures/demos/erc20_token.fe, crates/test-files/fixtures/printing/defs.fe, crates/test-files/fixtures/printing/expr_parens.fe, crates/test-files/fixtures/printing/guest_book_no_comments.fe, newsfragments/540.internal.md
We can't print the AST.
I wanted to fix #531 by adding a `$` to the front of lowered tuple struct names (e.g. `$tuple_bool_u256`), but wasn't able to do so without breaking the lowering tests. This is because the lowering tests compare the RON serialized AST of a lowered source file to that of an AST from a parsed file. So by adding a character to the lowered AST that is illegal to the parser, we are unable to validate that part of the lowering phase.
By making the AST printable, we can replace the existing lowering tests with insta snapshots and not have to be bound by grammar rules when lowering.
=> Pretty printing of Fe AST

docs/src/quickstart/first_contract.md
Dangling "python" language specifier above code block
Remove unnecessary "python"
=> Remove minor typo

crates/lowering/src/mappers/expressions.rs, crates/lowering/tests/snapshots/lowering__module_const.snap, crates/lowering/tests/snapshots/lowering__return_unit.snap, crates/parser/src/ast.rs, crates/test-files/fixtures/lowering/module_const.fe
We missed to lower expressions inside list expressions.
Call to `expr`
I didn't create a release notes entry for this because I don't think that in previous releases there was a way for an user to hit this bug. But they can hit it now with the `const` support.
=> Ensure expressions in list expressions are lowered

docs/src/development/release.md
Our release guide did not mention that we need to update the website after each release.
:writing_hand:
=> Expanded release guide to include website & docs

.github/workflows/main.yml, crates/analyzer/src/errors.rs, crates/tests/src/differential.rs
`cargo test --workspace --all-features` takes too long when running locally.
I `#[ignore]`d the proptest-based tests, and added a `--include-ignored` flag to the gh workflow so they still run there.
They can be run separately with something like `cargo test --workspace --all-features -- --ignored`
=> Make differential proptests opt-in (via --include-ingored)

.github/workflows/expensive.yml, .github/workflows/main.yml, crates/test-files/fixtures/differential/math_i8.sol, crates/tests/src/differential.rs
We recently added differential tests that aim to find bugs through fuzzing certain contracts with random inputs. These tests do not work well for the PR CI runs because:
- They may discover bugs which then causes a PR to fail for an unrelated reason
- They take a long time to run
- They should run as often as possible
- Moved it into a cron job to run every 30 minutes. This was chosen as a sweet spot to run it as often as possible without clogging our CI queue (leaving room for PR jobs etc)
- When a job fails, the `differential.txt` is read and presented which give us a chance to add the seed to version control as a regression test.
- Ideally, we would like to create a github issue automatically but that's a job for another day because we will need to come up with something that first …
=> Re-enable differential testing as a cronjob

crates/analyzer/src/db/queries/module.rs, crates/analyzer/src/traversal/call_args.rs, crates/analyzer/tests/analysis.rs, crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/analysis__call_statement_with_args.snap, crates/analyzer/tests/snapshots/analysis__call_statement_with_args_2.snap, crates/analyzer/tests/snapshots/analysis__call_statement_without_args.snap, crates/analyzer/tests/snapshots/analysis__erc20_token.snap, crates/analyzer/tests/snapshots/analysis__pure_fn_standalone.snap, crates/analyzer/tests/snapshots/analysis__uniswap.snap, crates/common/src/diagnostics.rs, crates/common/src/files.rs, crates/common/src/span.rs, crates/driver/src/lib.rs, crates/fe/src/main.rs, crates/lowering/src/utils.rs, crates/lowering/tests/lowering.rs, crates/parser/src/ast.rs, crates/parser/src/grammar/module.rs, crates/parser/src/lexer.rs, crates/parser/src/lib.rs, crates/parser/src/parser.rs, crates/parser/tests/cases/errors.rs, crates/parser/tests/cases/parse_ast.rs, crates/parser/tests/cases/print_ast.rs, crates/test-utils/src/lib.rs, crates/tests/src/crashes.rs, newsfragments/587.internal.md
https://github.com/ethereum/fe/blob/bfeffe82b4f8623330c1ebb1950ca981449c9e86/crates/common/src/diagnostics.rs#L8-L11
We also can't get a list of diagnostics with labels pointing to different source files.
Refactored things.
=> Attach file IDs to `Span`s

crates/analyzer/src/traversal/expressions.rs, crates/test-files/fixtures/crashes/agroce550.fe, crates/test-files/fixtures/features/return_bitwiseshl_i64_coerced.fe, crates/tests/src/crashes.rs, crates/tests/src/features.rs, newsfragments/550.bugfix.md
Fixes #550
The following code crashes:
```
let my_array: i256[1] = [-1 << 1] 
```
The interesting part is that this crashes **after lowering** with the following error:
>The right hand side of the `>>` operation must be unsigned"
Clearly, the right hand side **is** an unsigned integer so what's the problem here and why isn't it detected in the first analyzer pass?
The issue is that this gets lowered to something like this:
```
fn list_expr_array_i256_1(val0: i256) -> i256[1]:
let generated_array: i256[1]
generated_array[0] = val0
return generated_array
contract Foo:
pub fn o() -> ():
list_expr_array_i256_1(-1 >> 0)
return ()
```
Now that `-1 >> 0` is passed into the function `list_expr_array_i256_1` we try to coerce the types of both the left and the right hand side.
However, since only …
=> Don't coerce type of right hand side of binary operation

.github/workflows/main.yml, Makefile, crates/common/src/numeric.rs, crates/common/src/panic.rs, crates/lowering/src/ast_utils.rs, crates/lowering/src/context.rs, crates/lowering/src/lib.rs, crates/lowering/src/mappers/expressions.rs, crates/lowering/src/mappers/functions.rs, crates/lowering/src/utils.rs, crates/lowering/tests/lowering.rs, crates/lowering/tests/snapshots/lowering__and_or.snap, crates/lowering/tests/snapshots/lowering__ternary.snap, crates/parser/src/node.rs, crates/test-files/fixtures/features/short_circuit.fe, crates/test-files/fixtures/features/ternary_expression_with_revert.fe, crates/test-files/fixtures/lowering/and_or.fe, crates/test-files/fixtures/lowering/ternary.fe, crates/tests/src/features.rs, crates/yulgen/src/mappers/expressions.rs, newsfragments/488.bugfix.md
As described in #488 our current ternary expression doesn't short circuit but instead evaluates both branches and then discards one side of it.
1. Create some helpers to manipulate parts of the AST better
2. Used these helpers to lower ternary expressions in a way that maps them to an if/else followed by a simple name expression
=> Lower ternary and boolean expressions

crates/tests/src/runtime.rs, crates/yulgen/src/runtime/functions/data.rs
The `ternary` runtime function should have been deleted in the PR that lowers ternary expressions to `if`/ `else` statements but it wasn't.
Deleted dead code
=> Remove ternary runtime function

crates/test-files/fixtures/features/arrays.fe, crates/test-utils/src/lib.rs, crates/tests/src/features.rs, crates/yulgen/src/constants.rs, crates/yulgen/src/operations/data.rs, crates/yulgen/src/runtime/functions/data.rs, newsfragments/606.feature.md
We do not yet revert with a proper `Panic(0x32)` when trying to access an array item that is not within the bounds of the array.
- Added a `get_array_item` function that handles the check and used it in the `indexed_array` operation
- Added tests
=> Revert with proper panic if array index out of bounds

crates/analyzer/src/traversal/expressions.rs
comment typo
assigment -> assignment
=> Fix typo in expressions.rs

Cargo.lock, crates/test-utils/Cargo.toml, crates/tests/Cargo.toml, crates/yulc/Cargo.toml, crates/yulgen/Cargo.toml
The build of the latest solc-rust commit is broken on gh workflow's mac environment.
We should be using a specific git revision id for all git dependencies anyway, so that we have control of when exactly the changes to those repositories land in fe.
Specified a git "rev" for the solc-rust and yultsur dependencies. solc-rust is set to the commit that uses solc 0.8.4 for now.
(See https://github.com/ethereum/solidity/pull/12408)
=> Use specific commit for solc-rust (solc 0.8.4) and yultsur (latest)

crates/test-utils/Cargo.toml, crates/tests/Cargo.toml
Running only the `fe-compiler-tests` with `cargo test -p fe-compiler-tests --features solc-backend` fails because the `solc-backend` feature did not enable that feature in `test-utils`. Further, `test-utils` depends on `solc-backend` being enabled in `fe-driver` in the situation that `test-utils/solc-backend` is enabled. 
Added relevant features in `tests` and `test-utils` crate to enable the same conditional features in appropriate dependencies.
=> Fix feature flags in test & test-utils

Cargo.lock, crates/test-utils/Cargo.toml, crates/yulc/Cargo.toml, crates/yulc/src/lib.rs
We were using solc 0.8.4, which doesn't support the (London) basefee opcode.
solc 0.8.10 breaks the mac ci build, so 0.8.7 it is for now.
Closes #108 I suppose.
Updated solc-rust to solc 0.8.7. I also removed bindgen from the dependency graph to speed up builds a hair.
=> Update solc to 0.8.7

Cargo.lock, crates/abi/Cargo.toml, crates/analyzer/Cargo.toml, crates/analyzer/src/db/queries/events.rs, crates/analyzer/src/db/queries/functions.rs, crates/analyzer/src/namespace/types.rs, crates/analyzer/src/traversal/declarations.rs, crates/analyzer/src/traversal/expressions.rs, crates/analyzer/src/traversal/types.rs, crates/analyzer/src/traversal/utils.rs, crates/common/Cargo.toml, crates/common/src/files.rs, crates/driver/Cargo.toml, crates/fe/Cargo.toml, crates/lowering/Cargo.toml, crates/lowering/src/mappers/functions.rs, crates/parser/Cargo.toml, crates/test-files/Cargo.toml, crates/test-files/src/lib.rs, crates/test-utils/Cargo.toml, crates/tests/Cargo.toml, crates/yulc/Cargo.toml, crates/yulgen/Cargo.toml, crates/yulgen/src/db/queries/contracts.rs, crates/yulgen/src/mappers/assignments.rs, crates/yulgen/src/mappers/expressions.rs, fuzz/Cargo.toml
I didn't feel like doing anything challenging.
Did some mindless chores. Find and replace, deleted now-unnecessary `TryInto` `use`s, etc, ran `cargo outdated` a couple times. I didn't update a few things that would have required code changes that I didn't want to make.
@g-r-a-n-t Note the `include_dir` change in test-files. You might need to do the same for the new library crate.
=> Rust 2021, update (most) dependencies

.github/workflows/expensive.yml, .github/workflows/main.yml, Cargo.toml, docs/validate_doc_examples.py
Github CI builds are slow.
The rust-cache action is doing most of the work here, but I made a few other tweaks too. The test jobs now take 2-3 minutes instead of 20-25. Installing boost is about a third of this. I had been using an apt cache action, but then the coverage build failed mysteriously on a failure to find boost, so I scrapped that. I'll either revisit that someday, or maybe just install the few boost libs that solc actually uses.
The coverage job is still slow (~20min now instead of 35). I'm tempted to remove it from the PR workflow so that finishes quickly, and just let it run on merges to master or something. We aren't using coverage stats to judge the test cases of PRs anyway.
Oh, I bumped the proptest job to run every 60 minutes, just to reduce our resource consumption a …
=> CI speedup

Cargo.lock, crates/analyzer/src/builtins.rs, crates/analyzer/src/context.rs, crates/analyzer/src/db/queries/functions.rs, crates/analyzer/src/namespace/items.rs, crates/analyzer/src/namespace/scopes.rs, crates/analyzer/src/namespace/types.rs, crates/analyzer/src/traversal/expressions.rs, crates/analyzer/tests/analysis.rs, crates/lowering/src/mappers/module.rs, crates/test-files/fixtures/features/intrinsics.fe, crates/tests/src/features.rs, crates/yulgen/Cargo.toml, crates/yulgen/src/context.rs, crates/yulgen/src/db/queries/functions.rs, crates/yulgen/src/mappers/assignments.rs, crates/yulgen/src/mappers/declarations.rs, crates/yulgen/src/mappers/expressions.rs, crates/yulgen/src/mappers/functions.rs, newsfragments/603.feature.md
This adds yul's evm functions (with an added double-underscore prefix) as `unsafe` global functions. https://docs.soliditylang.org/en/latest/yul.html#evm-dialect
eg `mload` -> `__mload`
=> Intrinsics

crates/lowering/src/mappers/functions.rs, crates/lowering/tests/snapshots/lowering__module_const.snap, crates/test-files/fixtures/crashes/revert_const.fe, crates/tests/src/crashes.rs, newsfragments/619.bugfix.md
The `revert` arg expr wasn't being lowered, leading to a panic for certain code (eg code that uses a `const`)
:magic_wand:
=> Lower `revert` argument

crates/analyzer/src/traversal/expressions.rs, crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/errors__cast_address_to_u64.snap, crates/test-files/fixtures/features/cast_address_to_u256.fe, crates/tests/src/features.rs, newsfragments/621.feature.md
#614
Tiny change to the analyzer to make this cast not an error anymore.
=> Allow address-to-u256 cast

crates/lowering/src/names.rs, crates/lowering/tests/snapshots/lowering__list_expressions.snap, crates/test-files/fixtures/crashes/agroce623.fe, crates/test-files/fixtures/lowering/list_expressions.fe, crates/tests/src/crashes.rs, newsfragments/623.bugfix.md
Empty list expressions lead to an ICE
Lowering code produced wrong `TypeDesc` for generic arrays.
=> Properly resolve generic type desc

crates/analyzer/src/db/queries/contracts.rs, crates/analyzer/src/db/queries/functions.rs, crates/analyzer/src/db/queries/structs.rs, crates/analyzer/src/namespace/items.rs, crates/analyzer/src/namespace/types.rs, crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/analysis__structs.snap, crates/analyzer/tests/snapshots/errors__return_complex_struct.snap, crates/test-files/fixtures/compile_errors/return_complex_struct.fe, crates/test-files/fixtures/features/structs.fe, crates/tests/src/features.rs, crates/yulgen/src/db.rs, crates/yulgen/src/db/queries/structs.rs, crates/yulgen/src/mappers/assignments.rs, crates/yulgen/src/operations/structs.rs, newsfragments/343.feature.md
As described in #343 structs can currently only use fields with base types. That limitation should be lifted.
Structs can now use any fixed size type (except contract types for now) as field types. However, support is currently limited in two major ways:
- Structs with complex fields can not be returned from public functions
- Structs with complex fields can not be stored in storage
That functionality is expected to arrive with follow up PRs.
I should also say that the implementation based on `get_x_ptr` / `get_x_ptr_raw` feels a bit dirty (especially the part where we derive the `_raw` API from the non `raw` one). But this seems like something that would naturally evolve in another direction if we add explicit reference semantics so it may be ok for now.
=> Support non-base type fields in structs

crates/test-files/fixtures/features/return_from_storage_array_i8.fe, crates/test-files/fixtures/features/return_int_array.fe, crates/test-files/fixtures/solidity/arrays.sol, crates/test-utils/src/lib.rs, crates/tests/src/differential.rs, crates/tests/src/features.rs, crates/tests/src/runtime.rs, crates/tests/src/solidity.rs, crates/yulgen/src/operations/abi.rs, crates/yulgen/src/runtime/functions/abi.rs, newsfragments/633.bugfix.md
We weren't `signext`ing int array elements when encoding (see #581).
Added a `signed` parameter to the `abi_unpack` Yul method. If this value is set true, each element will be `signext`ed when unpacked.
=> signext unpacked ints

crates/analyzer/src/traversal/expressions.rs, crates/test-files/fixtures/crashes/agroce551.fe, crates/tests/src/crashes.rs, newsfragments/551.bugfix.md
A certain unprintable ASCII char lead to an ICE (#551)
This was due to an off-by-one error in our ASCII validation. That char should have been recognized as illegal.
=> Fixed a crash with a certain unprintable ASCII char

crates/parser/src/grammar/expressions.rs, crates/parser/tests/cases/snapshots/cases__errors__expr_dotted_number.snap
Compiling `my_array[0] = 0.15` throws:
```
Unable to compile ./local/decimal.fe.
error: failed to parse attribute expression
┌─ ./local/decimal.fe:4:25
│
4 │         my_array[0] = 0.15
│                         ^^ expected a name
```
https://github.com/ethereum/fe/issues/224
Added case to check for float
```
Unable to compile ./local/decimal.fe.
error: floats not supported
┌─ ./local/decimal.fe:4:23
│
4 │         my_array[0] = 0.15
│                       ^^^^
```
=> Improve parser error message when float is encountered

crates/fe/src/main.rs
As stated in #641 , the `solc-backend` panics when a non-existent path is passed to it as an argument because `unwrap` was called directly on `entry` assuming that it is always `Ok` and not an `Err`. (in other words, directory errors were unhandled)
Just added a checker before calling `unwrap`, this would exit the process with code `1` and avoids panic.
```rust
for entry in walker {
if entry.is_err() {
eprintln!("Error: {}", entry.unwrap_err());
std::process::exit(1)
}
let entry = entry.unwrap();
.......
```
Every item returned by the iterator is of type `Result<walkdir::DirEntry, walkdir::Error>`, so `entry.is_err()` check  needs to be called for each item. An alternative solution would be to check if the path exists before the for loop, but that would not guarantee that every item in …
=> Fix: Prevent solc-backend panic when non-existent path is passed to it as argument. (Fixes issue #641)

crates/analyzer/src/db/queries/contracts.rs, crates/analyzer/src/namespace/items.rs, crates/analyzer/tests/snapshots/analysis__structs.snap, crates/test-files/fixtures/features/structs.fe, crates/tests/src/features.rs, crates/yulgen/src/db.rs, crates/yulgen/src/db/queries/structs.rs, crates/yulgen/src/mappers/assignments.rs, crates/yulgen/src/mappers/expressions.rs, crates/yulgen/src/operations/structs.rs, newsfragments/636.feature.md
We need to support complex structs (such that have non-base type fields) in storage.
It's a first rough version that is wasteful:
1. We copy the entire struct from memory to storage *including* the memory references even though these are never read or written to and just waste storage in memory. The only reason is convenience because it lets us treat all getters for the base type fields in the same way. We can fix that later :D
2. Then, we copy all the reference type fields to storage using the very same compile time storage reference scheme that we use for `Map<T>` types.
=> Support complex structs in storage

docs/book.toml
`https://goerli.etherscan.io/` rejects requests from lintkcheck.
Just excluded `goerli.ehterscan.io`.
=> Exclude `goerli.etherscan.io` from linkcheck

crates/analyzer/src/traversal/expressions.rs, crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/analysis__strings.snap, crates/analyzer/tests/snapshots/errors__bad_string.snap, crates/analyzer/tests/snapshots/errors__call_event_with_wrong_types.snap, crates/test-files/fixtures/compile_errors/bad_string.fe, crates/test-files/fixtures/compile_errors/call_event_with_wrong_types.fe, crates/test-files/fixtures/features/strings.fe
Semantic analysis for string is too strict.
```python
let s: String<10> = "FOO"
```
should be accepted.
=> Allow assignments from smaller string type to larger string type

Makefile
Our website was out of date (showing `0.11.0` from December to download). This is because we currently need to redeploy our (static) website whenever we cut a new release.
Not really but adding a bold red note to show after we push a release to Github.
=> Add a red-bold hint to remember to update the website

.github/workflows/expensive.yml, .github/workflows/main.yml
Currently, installing dependency fails in CI because package index points removed a dependent package(`libxnvctrl0_470.57.01-0ubuntu0.20.04.2_amd64.deb`).
add `apt-get update` before `apt install ...`.
ref: https://github.com/actions/virtual-environments/issues/2924
ref: https://docs.github.com/en/actions/using-github-hosted-runners/customizing-github-hosted-runners
=> Add `apt update` in CI

crates/test-files/fixtures/differential/storage_and_memory.fe
The differential test has been broken since `context` was introduced.
Use `ctx.block_number()` instead of `block.number`
=> Fix differential test

crates/yulgen/src/runtime/functions/data.rs, newsfragments/684.bugfix.md
The region of memory used to compute the slot of a storage map value was not being allocated.
:keyboard: 
=> fixed memory bug in storage maps

Makefile
With the introduction of `linkcheck`, the final artifacts of the book are now placed under `docs/html/` not `docs/`, so the makefile needs to be modified.
=> Fix makefile to properly locate book

crates/analyzer/src/db/queries/functions.rs, crates/analyzer/tests/snapshots/errors__unsafe_misuse.snap, crates/test-files/fixtures/compile_errors/unsafe_misuse.fe
`unsafe` functions weren't allowed to be public (`pub`) as described in #687 
The issue was fixed by removing the block of code that checked whether the function is both `pub` and `unsafe`. i.e by removing the [following check](https://github.com/ethereum/fe/blob/master/crates/analyzer/src/db/queries/functions.rs#L30-L39).
Later, the tests were updated to respect the same by updating the snapshots using `cargo insta review`.
=> Allow public unsafe smart contract functions to be called from outside

crates/lowering/src/mappers/functions.rs, crates/lowering/src/mappers/module.rs, crates/parser/src/ast.rs, crates/parser/src/grammar/functions.rs, crates/parser/tests/cases/parse_ast.rs, crates/parser/tests/cases/snapshots/cases__parse_ast__contract_def.snap, crates/parser/tests/cases/snapshots/cases__parse_ast__fn_def_generic.snap, crates/parser/tests/cases/snapshots/cases__parse_ast__fn_def_pub.snap, crates/parser/tests/cases/snapshots/cases__parse_ast__fn_def_pub_unsafe.snap, crates/parser/tests/cases/snapshots/cases__parse_ast__fn_def_unsafe.snap, crates/parser/tests/cases/snapshots/cases__parse_ast__guest_book.snap, crates/parser/tests/cases/snapshots/cases__parse_ast__module_level_events.snap, crates/parser/tests/cases/snapshots/cases__parse_ast__module_stmts.snap, crates/parser/tests/cases/snapshots/cases__parse_ast__pub_contract_def.snap, crates/parser/tests/cases/snapshots/cases__parse_ast__struct_def.snap
We don't parse generic functions yet e.g. `fn do_it<T, E: Event>(me: T, eek: E):`
Parse dat thing
=> Parse generic function definitons

crates/tests/src/snapshots/fe_compiler_tests__demo_uniswap__uniswap_contracts.snap, crates/yulgen/src/runtime/abi_dispatcher.rs, crates/yulgen/tests/snapshots/yulgen__abi_dispatcher.snap, newsfragments/694.bugfix.md
Otherwise, there would currently be no way to send ETH
to a contract.
=> Return instead of revert when contract is called without data

crates/analyzer/src/db.rs, crates/analyzer/src/db/queries/structs.rs, crates/analyzer/src/namespace/items.rs, crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/errors__struct_recursive_cycles.snap, crates/test-files/fixtures/compile_errors/struct_recursive_cycles.fe, newsfragments/682.bugfix.md
As stated by @Y-Nak in the issue #682 
By adding `struct_cycles` as salsa cycle callback that throws an error when cycles are detected.
=> Detect cyclic field definitions in struct dependency graph

crates/abi/src/builder.rs, crates/abi/src/elements.rs, newsfragments/705.feature.md
The ABI metadata that we generate does currently not include the `stateMutability` field. This piece of information is important for tooling such as hardhat because it determines whether a function needs to be called with or without sending a transaction.
As soon as we have support for `mut self` and `mut ctx` we will be able to derive that information from the function signature. In the meantime we should default to `payable`. 
Add `stateMutability` field and default it to `payable`.
=> Temporary default stateMutability to payable in ABI

newsfragments/249.feature.md, newsfragments/442.feature.md, newsfragments/590.bugfix.md, newsfragments/681.bugfix.md, newsfragments/709.bugfix.md
#676 was so epic that nobody cared for the missing newsfragments
Added the missing newsfragments
=> Add missing newsfragments

crates/parser/src/grammar/expressions.rs, crates/parser/tests/cases/parse_ast.rs, crates/parser/tests/cases/snapshots/cases__parse_ast__expr_call3.snap, crates/parser/tests/cases/snapshots/cases__parse_ast__expr_call4.snap, newsfragments/719.feature.md
The following expressions would not parse:
https://github.com/ethereum/fe/blob/e661fb6ef6de87d3db26a4aad7180400e172024d/crates/parser/tests/cases/parse_ast.rs#L71-L72
Handle call expressions on the rhs when parsing attributes.
This feels hacky, so feel free to suggest better approaches,
=> Parsing attribute calls with generic args.

crates/abi/src/function.rs, newsfragments/722.bugfix.md
The new ABI crate that landed with #676 did not have the `stateMutability` field included. It should default to `payable` for now.
This is what #705 did but for the new ABI crate
=> Fix regression of stateMutability not being included in ABI

crates/codegen/src/yul/isel/function.rs, crates/mir/src/ir/value.rs, newsfragments/723.bugfix.md
1. Right shift operation isn't lowered `sar` when operands are signed type
2. negate operation isn't lowered into `safe_sub` call.
🔪 
=> Fix wrong safemath lowering

.github/workflows/coverage.yml, .github/workflows/main.yml
The cargo-tarpaulin check takes 20+ minutes. The rest are usually done in <4 minutes. Fast checks and not wasting compute resources are nice things. Our test coverage never changes much; someone should make a concerted effort to improve it, but they can run cargo-tarpaulin locally and/or make the code coverage check run on their pr by changing the workflow file.
Moved the code coverage check into a new workflow file that only runs when something is pushed to master.
=> GH actions: run test coverage on merge-to-master, but not prs

crates/abi/src/types.rs, crates/analyzer/src/namespace/types.rs, crates/analyzer/src/operations.rs, crates/analyzer/src/traversal/expressions.rs, crates/analyzer/src/traversal/functions.rs, crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/analysis__abi_decode_complex.snap, crates/analyzer/tests/snapshots/analysis__abi_encoding_stress.snap, crates/analyzer/tests/snapshots/analysis__address_bytes10_map.snap, crates/analyzer/tests/snapshots/analysis__data_copying_stress.snap, crates/analyzer/tests/snapshots/analysis__events.snap, crates/analyzer/tests/snapshots/analysis__external_contract.snap, crates/analyzer/tests/snapshots/analysis__keccak.snap, crates/analyzer/tests/snapshots/analysis__multi_param.snap, crates/analyzer/tests/snapshots/analysis__return_array.snap, crates/analyzer/tests/snapshots/analysis__sized_vals_in_sto.snap, crates/analyzer/tests/snapshots/analysis__structs.snap, crates/analyzer/tests/snapshots/analysis__tuple_stress.snap, crates/codegen/src/db/queries/abi.rs, crates/codegen/src/yul/isel/function.rs, crates/codegen/src/yul/runtime/abi.rs, crates/mir/src/lower/types.rs, crates/test-files/fixtures/features/abi_decode_complex.fe, crates/test-files/fixtures/features/for_loop_with_complex_elem_array.fe, crates/tests/src/features.rs, crates/tests/src/snapshots/fe_compiler_tests__demo_uniswap__uniswap_contracts.snap, crates/tests/src/snapshots/fe_compiler_tests__features__abi_decode_complex.snap, crates/tests/src/snapshots/fe_compiler_tests__features__case_163.snap, newsfragments/730.feature.md, newsfragments/734.bugfix.md
close #730 
1. Allow using a complex type as an array element type
2. Fix a bug that incorrect instruction is selected when the operands of a comp instruction are a signed type.
Example: 
```
contract Foo {
pub fn bar() -> i256 {
let my_array: Array<Pair, 3> = [Pair::new(-1, 1), Pair::new(10, -10), Pair::new(-100, 100)]
let sum: i256 = 0
for pair in my_array {
sum += pair.l1_norm()
}
return sum
}
}
struct Pair {
pub x: i256
pub y: i256
pub fn new(_ x: i256, _ y: i256) -> Pair {
return Pair(x, y)
}
pub fn l1_norm(self) -> i256 {
return abs(self.x) + abs(self.y)
}
}
fn abs(_ val: i256) -> i256 {
if val < 0 {
return -val
} else {
return val
}
}
```
NOTE: 
Please start reviewing this after #729 is merged.
=> Allow using a complex type as an array element type

crates/analyzer/src/db/queries/contracts.rs, crates/analyzer/src/db/queries/functions.rs, crates/analyzer/src/db/queries/module.rs, crates/analyzer/src/namespace/items.rs, crates/analyzer/src/namespace/types.rs, crates/analyzer/src/operations.rs, crates/analyzer/src/traversal/expressions.rs, crates/analyzer/src/traversal/types.rs, crates/analyzer/tests/analysis.rs, crates/analyzer/tests/snapshots/errors__traits_as_fields.snap, crates/mir/src/lower/types.rs, crates/parser/src/grammar/functions.rs, crates/parser/tests/cases/errors.rs, crates/parser/tests/cases/snapshots/cases__errors__fn_invalid_bound.snap
This is a follow up to #710 which defined `Type::Trait`. Traits are currently only supported as bounds on generics. Since for the foreseeable future we do not plan to support traits in places where types are supported we should remove it from `Type` and instead create an `Item::Trait(TraitId)`
Pretty much what the description already spoiled.
=> Treat `trait` exclusively as `Item` not `Type`

crates/codegen/src/yul/isel/inst_order.rs, newsfragments/749.bugfix.md
close #749 
The problem is that the same basic block is included in serialized `StructuralInst` and then translated into yul more than once in the below CFG condition.
1. CFG doesn't have a canonical exit block
2. Two paths can be merged at a certain block
e.g.,
In this CFG, `bb2` is a `merge` block of two paths, `bb0 -> bb1 -> bb4 -> bb2` and `bb0 -> bb2`.
But the compiler can't find merge block properly, and it lead to ICE as a result.
I wrongly assumed that `if` merge block should be the post dominator of `if` header.
To find `if` merge block correctly, we should follow the below algorithm.
When we see the `branch` instruction in a non-loop header, we can find a merge block candidate by applying the following criteria to two destination blocks of the `branch` instruction respectively. …
=> Fix duplicated block in control flow uplifting

crates/analyzer/src/context.rs, crates/analyzer/src/db/queries/contracts.rs, crates/analyzer/src/db/queries/functions.rs, crates/analyzer/src/db/queries/impls.rs, crates/analyzer/src/db/queries/structs.rs, crates/analyzer/src/db/queries/traits.rs, crates/analyzer/src/namespace/items.rs, crates/analyzer/src/namespace/scopes.rs, crates/analyzer/src/namespace/types.rs, crates/analyzer/src/traversal/expressions.rs, crates/analyzer/tests/analysis.rs, crates/analyzer/tests/snapshots/errors__self_in_standalone_fn.snap, crates/analyzer/tests/snapshots/errors__self_misuse.snap, crates/codegen/src/db/queries/function.rs, crates/mir/src/db/queries/function.rs, crates/mir/src/lower/function.rs, crates/test-files/fixtures/features/generic_functions_primitves.fe, crates/tests/src/features.rs, newsfragments/710.feature.md
Currently traits can only be implemented for structs. The reason for that is that prior to monomorphization we do not know the `Location` of a type generic type (e.g. `T`) and for that reason hard coded it to `Location::Memory` which would exclude primitive types such as `u8`.
I made attempts to get rid of `Location` in the analyzer entirely but I kept failing. Then I realized that we actually don't yet allow to assign generic arguments anyway. Since the location is only relevant for when variables are assigned we could have used `Location::Value` and it would have worked exactly the same, it's superfluous information for now.
Hence, I thought we could introduce a `Location::Unresolved` for now and in return lift the restriction to allow traits to be implemented for all base types, arrays …
=> Allow traits to be implemented for almost all types

crates/analyzer/src/context.rs, crates/analyzer/src/db.rs, crates/analyzer/src/db/queries/functions.rs, crates/analyzer/src/db/queries/types.rs, crates/analyzer/src/namespace/items.rs, crates/analyzer/src/namespace/types.rs, crates/analyzer/src/traversal/expressions.rs, crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/errors__ambiguous_traits.snap, crates/analyzer/tests/snapshots/errors__ambiguous_traits2.snap, crates/analyzer/tests/snapshots/errors__bad_ingot.snap, crates/analyzer/tests/snapshots/errors__bad_visibility.snap, crates/analyzer/tests/snapshots/errors__duplicate_struct_in_module.snap, crates/analyzer/tests/snapshots/errors__trait_not_in_scope.snap, crates/test-files/fixtures/compile_errors/ambiguous_traits.fe, crates/test-files/fixtures/compile_errors/ambiguous_traits2.fe, crates/test-files/fixtures/compile_errors/trait_not_in_scope/src/foo.fe, crates/test-files/fixtures/compile_errors/trait_not_in_scope/src/main.fe, crates/test-files/fixtures/features/generic_functions.fe, crates/test-files/fixtures/features/generic_functions_primitves.fe, crates/test-files/fixtures/features/simple_traits.fe, crates/tests/src/features.rs, crates/tests/src/snapshots/fe_compiler_tests__features__case_1_generic_functions.snap, crates/tests/src/snapshots/fe_compiler_tests__features__case_1_simple_traits.snap, crates/tests/src/snapshots/fe_compiler_tests__features__case_2_generic_functions.snap, crates/tests/src/snapshots/fe_compiler_tests__features__case_2_generic_functions_primitves.snap, crates/tests/src/snapshots/fe_compiler_tests__features__case_3_generic_functions_primitves.snap, newsfragments/757.feature.md
Traits can't currently be used without generics but they should be.
Example of what the PR enables:
```rust
trait Double {
fn double(self) -> u256;
}
impl Double for (u256, u256) {
fn double(self) -> u256 {
return (self.item0 + self.item1) * 2
}
}
contract Example {
pub fn run_test(self) {
assert (0, 1).double() == 2
}
}
```
Some notes:
- If a call turns out to be ambigious the compiler currently asks the user to disambiguate via renaming. In the future we will likely introduce a syntax to allow to disambiguate at the callsite.
- refactored to get rid of `Class` entirely (it's not too useful as a concept since via `impl` and traits any type can have member functions)
- Ensured we fetch all impls even from foreign ingots. E.g. ingot `Foo` may have a struct `Thingy` and a trait `SuperPower` …
=> Allow trait methods to be called on non-generic types if trait is in scope

crates/analyzer/src/namespace/items.rs, crates/analyzer/src/traversal/expressions.rs, crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/analysis__struct_fns.snap, crates/analyzer/tests/snapshots/errors__call_non_pub_fn_on_external_contract.snap, crates/analyzer/tests/snapshots/errors__call_non_pub_fn_on_struct.snap, crates/analyzer/tests/snapshots/errors__call_non_pub_fn_on_struct2.snap, crates/test-files/fixtures/compile_errors/call_non_pub_fn_on_struct.fe, crates/test-files/fixtures/compile_errors/call_non_pub_fn_on_struct2.fe, crates/test-files/fixtures/features/contract_pure_fns.fe, crates/test-files/fixtures/features/pure_fn_internal_call.fe, crates/test-files/fixtures/features/simple_traits.fe, crates/test-files/fixtures/features/struct_fns.fe, crates/tests/src/features.rs, crates/tests/src/snapshots/fe_compiler_tests__features__case_056.snap, crates/tests/src/snapshots/fe_compiler_tests__features__case_161_struct_fns.snap, crates/tests/src/snapshots/fe_compiler_tests__features__case_4_contract_pure_fns.snap, newsfragments/767.bugfix.md, newsfragments/767.feature.md
The code that validates the visibility rules of function calls is duplicated, faulty and incomple.
1. Created a single function `validate_visibility_of_called_fn` that can be called from any place that needs to enforce the rules
2. Ensured the rules are enforced for calls to associated functions
3. Added a bunch more tests
4. Bonus: Made it possible to use `MyContract::static_func()` syntax which wasn't yet possible for contracts (but worked for structs)
5. More test coverage
=> Fix enforcement of visibility rules of function calls

crates/analyzer/src/namespace/items.rs, crates/test-files/fixtures/features/generic_functions.fe, newsfragments/773.bugfix.md
It is not possible to implement a trait that is defined in another ingot or even just another module.
Do not just look for implementations in the module of the trait but everywhere.
=> Ensure traits from other modules can be implemented

crates/analyzer/src/traversal/expressions.rs, crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/analysis__basic_ingot.snap, crates/analyzer/tests/snapshots/analysis__external_contract.snap, crates/analyzer/tests/snapshots/analysis__two_contracts.snap, crates/analyzer/tests/snapshots/analysis__uniswap.snap, crates/analyzer/tests/snapshots/errors__call_to_pure_fn_on_self.snap, crates/analyzer/tests/snapshots/errors__call_to_pure_struct_fn_on_instance.snap, crates/test-files/fixtures/compile_errors/call_to_pure_struct_fn_on_instance.fe, crates/test-files/fixtures/compile_errors/external_call_type_error.fe, crates/test-files/fixtures/compile_errors/external_call_wrong_number_of_params.fe, crates/test-files/fixtures/compile_errors/init_call_on_external_contract.fe, crates/test-files/fixtures/compile_errors/mislabeled_call_args_external_contract_call.fe, crates/test-files/fixtures/demos/uniswap.fe, crates/test-files/fixtures/features/ctx_param_external_func_call.fe, crates/test-files/fixtures/features/external_contract.fe, crates/test-files/fixtures/features/two_contracts.fe, crates/test-files/fixtures/ingots/basic_ingot/src/bing.fe, crates/test-files/fixtures/ingots/pub_contract_ingot/src/main.fe, crates/test-files/fixtures/stress/external_calls.fe, crates/tests/src/features.rs, crates/tests/src/snapshots/fe_compiler_tests__demo_uniswap__uniswap_contracts.snap, crates/tests/src/snapshots/fe_compiler_tests__features__external_contract.snap, newsfragments/775.bugfix.md
There were certain cases were the compiler did not reject code where a pure fn was called on an instance.
Minor tweak
=> Reject pure functions being called on instances

crates/analyzer/tests/snapshots/analysis__const_generics.snap, crates/analyzer/tests/snapshots/analysis__const_local.snap, crates/analyzer/tests/snapshots/analysis__guest_book.snap, crates/analyzer/tests/snapshots/analysis__uniswap.snap, crates/analyzer/tests/snapshots/errors__call_create2_with_wrong_type.snap, crates/analyzer/tests/snapshots/errors__call_create_with_wrong_type.snap, crates/library/std/src/evm.fe, crates/library/std/src/traits.fe, crates/parser/src/lexer.rs, crates/parser/src/lexer/token.rs, crates/test-files/fixtures/compile_errors/bad_tuple_attr1.fe, crates/test-files/fixtures/compile_errors/bad_tuple_attr2.fe, crates/test-files/fixtures/compile_errors/bad_tuple_attr3.fe, crates/test-files/fixtures/compile_errors/call_create2_with_wrong_type.fe, crates/test-files/fixtures/compile_errors/call_create_with_wrong_type.fe, crates/test-files/fixtures/compile_errors/struct_recursive_cycles.fe, crates/test-files/fixtures/compile_errors/undefined_type_param.fe, crates/test-files/fixtures/demos/guest_book.fe, crates/test-files/fixtures/demos/simple_open_auction.fe, crates/test-files/fixtures/demos/uniswap.fe, crates/test-files/fixtures/features/const_generics.fe, crates/test-files/fixtures/features/const_local.fe, docs/src/spec/comments.md, docs/theme/custom-highlight.js, newsfragments/776.feature.md, website/index.html
It seems like we have consensus that we don't want to continue to use `#` for comments but rather use `//` instead. This PR changes that.
- Tiny change in the parser
- Updated code files
- Updated examples + docs
- Updated highlight.js on the website to use the custom `fe` highlighting that the docs already use
=> Change comments from using `#` to using `//`

docs/src/quickstart/deploy_contract.md, docs/src/quickstart/first_contract.md
- As far as I understand, the docs referenced an outdated build command for the guest book contract demo
- Replaced build command instances of `./fe <TARGET>` with `./fe build <TARGET>`
=> Documentation Build Command

docs/src/quickstart/deploy_contract.md
1.  The prompt command ethsign import --keystore ~/.ethereum/keystore/   will result in an error saying it is an incorrect usage.
2. Transaction failing and ETH_GAS warning when deploying contract and signing the guest book.
1. Changed command to  ethsign import -key-store ~/.ethereum/keystore/
2.  Added ETH_GAS=8000000 in the deploy contract command and signing the guestbook command. Also added an explanation. I also removed the 'seth-send: warning: `ETH_GAS' not set; using default gas amount' description.
(My first PR, I'm a total beginner. Apologies for any mistakes)
=> deploy_contract.md edits

crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/errors__invalid_struct_pub_qualifier.snap, crates/parser/src/grammar/types.rs, crates/test-files/fixtures/compile_errors/invalid_struct_pub_qualifier.fe
Fix #787 
Before, the struct definitions like:
```
pub struct Bar {
pub x: i32
pub}
```
were not rejected by the parser. (as mentioned in #787 ). This pull request fixes this issue.
Also tests are written to validate this.
@Y-Nak
=> Properly parse struct definition by rejecting invalid public identifiers, Fixes: #787

crates/analyzer/src/context.rs, crates/analyzer/src/db/queries/contracts.rs, crates/analyzer/src/db/queries/structs.rs, crates/analyzer/src/namespace/types.rs, crates/analyzer/tests/snapshots/errors__contract_function_with_generic_params.snap, crates/analyzer/tests/snapshots/errors__enum_in_public_contract_sig.snap, crates/analyzer/tests/snapshots/errors__struct_recursive_cycles.snap
=> Forbid returning unencodable types from public contract functions

crates/analyzer/src/namespace/items.rs, crates/analyzer/src/namespace/types.rs, crates/analyzer/src/traversal/functions.rs, crates/analyzer/src/traversal/pattern_analysis.rs, crates/analyzer/tests/snapshots/analysis__enum_match.snap, crates/analyzer/tests/snapshots/errors__enum_match.snap, crates/codegen/src/db/queries/abi.rs, crates/mir/src/lower/pattern_match/mod.rs, crates/mir/src/lower/pattern_match/tree_vis.rs, crates/parser/src/ast.rs, crates/parser/src/grammar/functions.rs, crates/parser/tests/cases/errors.rs, crates/parser/tests/cases/parse_ast.rs, crates/parser/tests/cases/snapshots/cases__errors__stmt_match1.snap, crates/parser/tests/cases/snapshots/cases__parse_ast__stmt_match3.snap, crates/parser/tests/cases/snapshots/cases__parse_ast__stmt_match4.snap, crates/test-files/fixtures/compile_errors/enum_match.fe, crates/test-files/fixtures/features/enum_match.fe, crates/tests/src/features.rs, crates/tests/src/snapshots/fe_compiler_tests__features__enum_match.snap, docs/src/spec/statements/match.md, newsfragments/770.feature.md
Add a struct pattern that can be used in `match` statements.
e.g.,
```rust
struct MyS {
pub x: i32
pub b: bool
fn eval(self) -> i32 {
match self {
MyS {x: x, b: true} => {
return x
}
MyS {x: x, b: false} => {
return -x
}
}
}
}
```
1. Currently, field labels are required even if a binding name is the same as the field name.
2. To bind a field, the fields must be `pub`. Otherwise, the compiler complains about it.
```rust
enum Accumulator {
Zero
Int(u32)
Clo(i32, i32)
}
struct MyStruct {
pub acc: Accumulator
pub y: i32
}
contract Bar {
}
```
I noticed the above example still causes an ICE even in the current master.
In #798, I overlooked that we should modify `codegen/abi.rs` so that non-emittable structs are excluded from abi events.
I fixed the problem in this PR for testing a nested …
=> Struct pattern

README.md
URL of Uniswap example codes reference other branch not master
Fix URL
=> docs: example codes url correction

crates/test-files/fixtures/differential/math_u8.fe, crates/test-files/fixtures/differential/storage_and_memory.fe
`differential tests` failed because of missing `mut` feature modification.
Add the `mut` keyword to some variables where it's required.
=> Reflect `mut` feature to differential tests

crates/analyzer/src/context.rs, crates/analyzer/src/namespace/scopes.rs, crates/analyzer/src/traversal/borrowck.rs, crates/analyzer/src/traversal/expressions.rs, crates/analyzer/src/traversal/mod.rs, crates/analyzer/tests/snapshots/analysis__value_semantics.snap, crates/analyzer/tests/snapshots/errors__mut_mistakes.snap, crates/test-files/fixtures/compile_errors/mut_mistakes.fe, crates/test-files/fixtures/features/bountiful_struct_copy_bug.fe, crates/test-files/fixtures/features/value_semantics.fe, crates/tests/src/snapshots/fe_compiler_tests__features__value_semantics.snap, newsfragments/777.feature.md
fixes #810
This is a temporary solution to the only borrowing bug that's possible in the current semantics of Fe, namely passing a mutable reference to a non-primitive object into a fn call, and another reference to that same object (mutable or otherwise).
This is an ugly brute force solution that will definitely not scale beyond this simple case, and doesn't do anything smart like allow disjoint partial borrows.
This should be replaced with a proper borrow checker (presumably operating on MIR) when Fe gains some kind of reference/projection type.
=> Add dumb borrow check of fn call args

docs/book.toml
CI failed because the request to `alchemy.com` returns 403. 
I excluded `alchemy.com` from `linkcheck`. It would be better to set `follow-web-links = false` when more links start returning error status codes. But I think it's not the time yet.
=> Exclude `alchemy.com` from linkcheck

Cargo.lock, crates/analyzer/Cargo.toml, crates/parser/Cargo.toml, crates/test-utils/Cargo.toml, crates/tests/Cargo.toml
Cuts development and CI times.
Build: 211 crates
Check: 215 crates
Test: 312 crates
Build: 208 crates
Check: 212 crates
Test: 309 crates
=> Remove unused dependencies

README.md, website/index.html
People on Twitter reported that our discord invite link is dead
Replaced with fresh link
=> new discord link

.github/workflows/coverage.yml, .github/workflows/expensive.yml, .github/workflows/main.yml
Updated/removed some workflow dependencies to fix deprecate warnings.
* Remove deprecated docker container for wasm test.
* Replace `actions-rs/toolchain` with `dtolnay/rust-toolchain` Ref: https://github.com/actions-rs/toolchain/issues/216.
* Update `actions/checkout`.
*  Remove `actions-rs/cargo`.
=> Update workflows dependencies

docs/src/quickstart/deploy_contract.md, newsfragments/853.doc.md
The deployment guide was outdated in two ways:
1. The Görli network is deprecated and scheduled to sunset soon
2. Dapp.tools was a solid choice at the initial time of creating the tutorial but it was later rewritten in Rust and turned it its successor foundry
- Rewrote tutorial to use the Sepolia testnet which is now the recommended testnet for application development
- Rewrote tutorial to use foundry instead of dapp.tools
- fixed wording and typos
=> Use foundry and sepolia network in deployment guide

docs/src/spec/items/contracts.md
As stated in #792 we don't cover the `__init__` function yet
:writing_hand:
=> Cover __init__ function in contracts

crates/analyzer/src/db/queries/module.rs, crates/codegen/src/yul/runtime/data.rs, crates/mir/src/lower/pattern_match/decision_tree.rs, crates/tests-legacy/src/features.rs, docs/book.toml
New clippy = new failing lints
Also the mdbook linkcheck config needed to be adjusted for the tutorial update.
:open_hands:
=> Fix clippy for rust 1.68; ignore etherscan urls in book linkcheck

crates/analyzer/tests/snapshots/analysis__uniswap.snap, crates/test-files/fixtures/demos/uniswap.fe
Just a few tiny modernizations in the uniswap demo that I spotted while working on something else. In the future the whole demo should probably be converted to be split over multiple files to not repeat certain structs etc.
=> Modernize uniswap demo code

crates/analyzer/src/traversal/expressions.rs, crates/fe/src/task/test.rs, crates/mir/src/db/queries/function.rs, crates/mir/src/lower/function.rs, crates/test-files/fixtures/features/generic_functions.fe, crates/test-runner/src/lib.rs, newsfragments/861.bugfix.md
Invoking associated functions that take generics causes ICE.
e.g. given the following function `run`
```Rust
struct OperatingSystem {
pub run<T: Task>(task: T) {
task.run()
}
}
```
It will currently cause an ICE when `OperatingSystem::run(some_task)` is invoked.
Properly resolve generic parameters for associated functions
=> Fix resolving generics on associated fns

crates/analyzer/src/context.rs, crates/analyzer/src/namespace/types.rs, crates/analyzer/src/traversal/const_expr.rs, crates/analyzer/src/traversal/expressions.rs, crates/analyzer/src/traversal/types.rs, crates/analyzer/tests/snapshots/analysis__const_local.snap, crates/analyzer/tests/snapshots/analysis__erc20_token.snap, crates/analyzer/tests/snapshots/errors__mismatch_return_type.snap, crates/analyzer/tests/snapshots/errors__return_call_to_fn_with_param_type_mismatch.snap, crates/mir/src/ir/constant.rs, crates/parser/tests/cases/snapshots/cases__print_ast__erc20.snap, crates/test-files/fixtures/compile_errors/mismatch_return_type.fe, crates/test-files/fixtures/compile_errors/return_call_to_fn_with_param_type_mismatch.fe, crates/test-files/fixtures/demos/erc20_token.fe, crates/test-files/fixtures/features/const_local.fe, crates/tests/fixtures/files/const_local.fe, docs/src/spec/expressions/call.md, docs/src/spec/items/functions.md, docs/src/spec/items/visibility_and_privacy.md, docs/src/spec/type_system/types/address.md, newsfragments/864.feature.md
'twas impossible to define a `const` address, due to address values needing an explicit `address(...)` cast, which is treated as a function call internally, and thus not allowed in a `const` context yet.
Closes #809 (not exactly as stated, but with this change it's possible to define all primitive types in a const context so we don't need the type constructors/casts). This is an alternative to #862.
Allow number literals to be interpreted as an addresses. Anywhere an `address` type is expected, a number literal is allowed (as long as it fits in a u160).
```rust
const FOO: address = 0xfe // OK!
fn foo(a: address) { .. }
foo(100) // OK! 
// ^ note that this is decimal 100! Perhaps we should only allow hex literals?
```
This might feel a bit loosey-goosey, but I think it'll be fine in real …
=> address literals

crates/analyzer/src/namespace/types.rs, crates/analyzer/src/traversal/call_args.rs, crates/mir/src/lower/function.rs, crates/test-files/fixtures/features/generic_functions.fe, crates/tests-legacy/src/snapshots/fe_compiler_tests_legacy__features__execution_tests@generic_functions.fe.snap, newsfragments/865.feature.md
If generic parameters are marked as `mut` there is currently no way to call them as the analyzer doesn't recognize them as the same type.
Threw a bunch more `deref()` around
=> Fix issue where generic params that are `mut` can never be satisfied by the caller

Cargo.lock, crates/codegen/Cargo.toml, crates/test-utils/Cargo.toml, crates/tests-legacy/Cargo.toml, crates/yulc/Cargo.toml, docs/src/development/build.md
solc version bump. The build was failing on my machine due to a new warning introduced into a recent clang version, so I disabled the PEDANTIC option in the solc build config.
I also made forks of solc-rust and yultsur in the fe-lang org. Let's use these instead of bouncing between personal forks. Update these at will, of course.
=> solc 0.8.19; move solc-rust and yultsur repos to fe-lang

website/index.html
I was browsing the Fe language [website](https://fe-lang.org/) and noticed the copyright notice was out of date. This is not a huge concern, but considering the website has been updated in 2022 and 2023 updating the date to a range to reflect that seems like a good idea.
Updated the copyright notice in the footer of the website to be a range from 2021 (website first published) to 2023 (current year)
=> chore: update website copyright notice date

crates/analyzer/src/traversal/expressions.rs, crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/errors__call_method_in_storage.snap, crates/test-files/fixtures/compile_errors/call_method_in_storage.fe, newsfragments/881.bugfix.md
A regression caused the compiler to not properly reject code that is trying to call a method on an in-storage struct.
- Ensured the check happens on the **non-derefenced** type.
- Added a test case which we were missing and caused this regression to slip through
=> Fix issue where compiler doesn't reject method call on storage struct

crates/analyzer/src/db/queries/functions.rs, crates/analyzer/src/db/queries/module.rs, crates/analyzer/tests/errors.rs, crates/analyzer/tests/snapshots/errors___test_fn_params.snap, crates/analyzer/tests/snapshots/errors__ctx_not_ctx_type.snap, crates/test-files/fixtures/compile_errors/_test_fn_params.fe, crates/test-files/fixtures/compile_errors/ctx_not_ctx_type.fe, crates/tests/fixtures/files/address_bytes10_map.fe, crates/tests/fixtures/files/arrays.fe, crates/tests/fixtures/files/associated_fns.fe, crates/tests/fixtures/files/call_fn.fe, newsfragments/880.feature.md
`ctx`  couldn't be used in tests functions without a bit of hacking.
modified checks around the `ctx` param and updated tests.
=> `ctx` param in tests

crates/library/std/src/buf.fe, newsfragments/898.performance.md
The buf write implementation seems unnecessarily complicated.
Currently we allocate the exact `len` in memory for the buffer and ensure via `rewrite_slot` that we do not modify data outside of the buf's allocated region.
This PR changes the buf implementation so that an extra 31 bytes is allocated for bufs. This eliminates the need for a function like `rewrite_slot`.
:keyboard: 
=> Buf write simplification

crates/library/std/src/context.fe, crates/tests/fixtures/files/call_fn.fe, crates/tests/fixtures/files/calldata_reader.fe, crates/tests/fixtures/files/calldata_reader_extra.fe
Implementation of CalldataReader. An instance of CalldataReader can be created using ctx.calldata_reader().
=> Calldata reader 

README.md, docs/validate_doc_examples.py
Example in Readme doesn't work anymore
- Example needed some `mut`
- Added `README.md` in snippet validation
=> Fix error in README example

crates/parser2/src/parser/mod.rs, crates/parser2/src/parser/struct_.rs, crates/parser2/test_files/error_recovery/items/struct_.fe, crates/parser2/test_files/error_recovery/items/struct_.snap
NOTE: Please start reviewing this PR after the name resolution PR is merged.
This PR adds the ad-hoc check to the parser to improve error messages when a function is defined inside a `struct/contract` definition.
The reason for this ad-hoc check is
1. This error is difficult to recover properly with the current parser design, and the emitted error message is confusing.
2. We anticipate that this error would often happen in the transition period to Fe-V2.
=> Improve error recovery in parsing fields definition

crates/driver2/src/diagnostics.rs, crates/driver2/src/lib.rs, crates/hir-analysis/tests/test_db.rs, crates/hir/src/lib.rs, crates/parser2/src/parser/mod.rs, crates/parser2/src/parser/struct_.rs, crates/parser2/test_files/error_recovery/items/struct_.fe, crates/parser2/test_files/error_recovery/items/struct_.snap
NOTE: Please start reviewing after https://github.com/ethereum/fe/pull/909 is merged
The `SpannedHirDb` and `LowerHirDb` marker traits required `Self: Sized` in `as_lower_hir_db()` and `as_lower_hir_db()` methods.
This broke consistency with other db traits that implement `DbWithJar`. So I decided to add two jars for these two traits respectively.
As a result, users for these traits no longer need to implement `SpannedHirDb` and `LowerHirDb` manually; instead, those traits are automatically implemented when `#[salsa::db(hir::SpannedJar, hir::LowerJar)]` is specified.
E.g., the driver database would be like the below.
```rust
#[salsa::db(
common::Jar,
hir::Jar,
hir::LowerJar,
hir::SpannedJar,
hir_analysis::Jar,
Jar
)]
pub struct DriverDataBase {
storage: salsa::Storage<Self>,
}
```
=> Improve marker traits usability

crates/common/src/utils/files.rs, crates/fe/src/task/test.rs, newsfragments/913.feature.md
As described in #913, `fe test` should always fallback to assume the root project directory if no path is specified.
JUST DID IT! LIKE A PSYCHOPATH.
=> Use project root as default path for `fe test`

crates/analyzer/tests/snapshots/errors__emittable_not_implementable.snap, crates/library/std/src/buf.fe, crates/library/std/src/context.fe, crates/library/std/src/evm.fe, crates/library/std/src/precompiles.fe, newsfragments/917.feature.md
There were still some `std::evm` functions that used memory offset and length parameters instead of `MemoryBuffer`.
=> Finish buf refactor

crates/driver/src/lib.rs, crates/fe/src/task/test.rs, newsfragments/919.feature.md
There's currently no way to restrict `fe test` to only run a subset of tests
Added a `--filter <some-filter>` option to allow filtering the tests.
I initially had it as a separate optional input (e.g. fe filter . <some-filter>) but that means people have to specify the directory manually which can be annoying when hopping between different directories.
=> Allow filtering tests when running fe test

docs/src/quickstart/installation.md, docs/theme/reference.css
PR adds details on how to build from source to the installation guide in the docs. This is useful because:
a) the most recent binary release will not run on Ubuntu <23.X - this allows Ubuntu users to build for themselves between now and the next release.
b) some folks want to build from source to develop Fe and this wasn't previously documented on the site.
I also added a tiny piece of CSS that adds a narrow whitespace buffer around code blocks to make code-snippet heavy pages a bit easier to read.
=> [website: docs] adds detail to installation pages

docs/src/quickstart/deploy_contract.md
PR includes a rework of the existing deploy-contract quick start. 
The main change is that it prioritizes deploying on a local blockchain (Anvil) to start, then moves to a public network later.  This allows beginners to quickly get to grips with deploying code without having to find SepoliaETH and with the ability to use ephemeral accounts.
Also adds some detail to help beginners understand what is happening at each stage of the deployment.
=> [website:docs] rework 'deploy contract' quick-start

crates/codegen/src/yul/isel/test.rs, crates/tests/fixtures/files/assert_with_string.fe, newsfragments/926.bugfix.md
Yul codegen was failing to include string literals used in test assertions. This resulted in a compiler error.
Example:
```
#test
fn foo() {
assert false, "oops"
}
```
I had to reorder some statements dealing with the analyzer context in the Yul test lowering function.
=> Test assertion string bugfix

docs/src/SUMMARY.md, docs/src/contributing.md, docs/src/index.md
Adds introductory information to the docs landing page. @cburgdorf @g-r-a-n-t would love your input to help distil Fe's USP on this page.
Adds "Contributing" page explaining how people can get involved with building Fe.
=> [website/docs]: + intro & contributing pages

docs/src/contributing.md, docs/src/index.md
Broken Discord links, same issue with https://github.com/ethereum/fe/pull/849 but on different pages.
Old: https://discord.com/invite/yCT6NYBb
New: https://discord.com/invite/ywpkAXFjZH
=> Fix Discord Links in contributing.md and index.md

crates/driver/src/lib.rs, crates/fe/src/task/build.rs, crates/test-utils/src/lib.rs, crates/tests-legacy/src/crashes.rs, crates/yulc/src/lib.rs, newsfragments/947.feature.md
Currently, the compiler would only outputs the bytecode that is used for contract deployment but not the runtime bytecode that is later saved to storage and can be read out from the blockchain.
Being able to obtain the runtime bytecode is useful for contract verification.
Basically just expose the `deployedBytecode` that `solc` already gives us.
Note:
- I named the file `mycontract.runtime.bin` because I find the term *runtime bytecode* less ambigious than *deployed bytecode*
- Producing runtime bytecode is another variant of the `--emit` options. Note that the default did **NOT** change from `abi, bytecode` because there are certain contracts where we currently can not produce runtime bytecode for. These seem to be contracts that use `create`/`create2` in `__init__`.
- Related to the …
=> Include runtime_bytecode in artifacts

Cargo.lock, crates/driver/src/lib.rs, crates/fe/Cargo.toml, crates/fe/src/main.rs, crates/fe/src/task/build.rs, crates/fe/src/task/mod.rs, crates/fe/src/task/verify.rs, crates/test-utils/src/lib.rs, crates/tests-legacy/src/crashes.rs, crates/yulc/src/lib.rs, newsfragments/947.feature.md, newsfragments/948.feature.md
People need to be able to verify that a deployed contract matches the source code
that the author claims was used to deploy it. Previously, there was no simple
way to achieve this.
These are the steps to verify a contract with the `verify` command:
1. Obtain the project's source code locally.
2. Ensure it is the same source code that was used to deploy the contract. (e.g. check out a specific tag)
2. From the project directory run `fe verify <contract-address> <json-rpc-url>`
Example:
```bash
$ fe verify 0xf0adbb9ed4135d1509ad039505bada942d18755f https://example-eth-mainnet-rpc.com
It's a match!✨
Onchain contract:
Address: 0xf0adbb9ed4135d1509ad039505bada942d18755f
Bytecode: 0x60008..76b90
Local contract:
Contract name: SimpleDAO
Source file: …
```
=> Add verify command to allow verifying deployed contracts against local source code

docs/src/spec/items/contracts.md
Adds some details to the existing contracts page, bringing it in line with the equivalent pages in the Solidity and Vyper docs.
=> [website/docs]: add detail to contracts page

docs/src/SUMMARY.md, docs/src/std/index.md, docs/src/std/precompiles.md, newsfragments/944.doc.md
This PR adds a new page documenting the EVM precompiles included in Fe
=> [website/docs]: add page on EVM precompiles

docs/src/user-guide/installation.md
Installation guide should focus on brew as it is the easiest way of installing Fe at this point. Also as people pointed out Fe works fine on Windows via WSL.
:writing_hand:
=> Minor improvements for installation guide

crates/fe/src/task/verify.rs, newsfragments/951.bugfix.md
Some JSON-RPC APIs are picky about the `Content-Type` header for requests. We should provide it. See #951 
Provided
=> Supply Content-Type header to JSON-RPC call

docs/src/user-guide/installation.md
Currently a debug build is produced and the following command attempts to run a release version of the code that has never been built.
Adds the `-r` flag to the cargo build command to ensure the following step that checks for a successful build runs correctly.
Also adds instructions to change directories into the Fe repository directory before attempting to build (following current instructions step-by-step would lead to failures).
=> Correct install instructions for compiling from source

crates/fe/src/task/build.rs, crates/fe/src/task/check.rs, crates/test-utils/src/lib.rs, newsfragments/962.feature.md
Currently `fe build` always needs to be supplied with an `<input-path>` which can be annoying when jumping between directories.
The `fe build` command should instead try to figure out the `<input-path>` itself if no input path is given. This is already the behavior of the `fe test` command.
The same is true for `fe check`.
When `fe build` is given no `<input-path>`, it now defaults to the project's root directory (based on where a `fe.toml` is found) or falls back to the current directory if no `fe.toml` is found. 
The same is true for `fe check`
=> Default to project root if no input path specified

docs/src/SUMMARY.md, docs/src/user-guide/external_links.md, newsfragments/971.doc.md
There are some useful Fe examples (or even tooling) that are currently hard to find. We should have a place in our docs that just acts as a link reference to external sites. We have a good collection of links here that I want to compile for this: https://notes.ethereum.org/rNqHGm1zRk671RO_ijDDmg
Added a new Section "Useful external links" that is now home for links to projects, blog posts, videos etc.
=> Add new section for external links

crates/test-runner/src/lib.rs, docs/src/SUMMARY.md
Indentation was messed up so that the new section was in the wrong group
=> Fix indentation

crates/language-server/src/handlers/notifications.rs, crates/language-server/src/server.rs, crates/language-server/src/util.rs
The WASM build was failing due to `Uri::to_file_path` and `Uri::from_file_path` not being implemented for WASM targets.
I made a trait defined only for WASM targets which implements dummy functions
=> Dummy file path conversions to fix CI + WASM build

crates/analyzer/tests/errors.rs, crates/hir/src/hir_def/expr.rs, crates/hir/src/hir_def/stmt.rs, crates/hir/src/lower/expr.rs, crates/hir/src/lower/path.rs, crates/hir/src/lower/stmt.rs, crates/hir/src/span/expr.rs, crates/hir/src/span/item.rs, crates/hir/src/span/mod.rs, crates/hir/src/span/stmt.rs, crates/hir/src/span/transition.rs, crates/hir/src/span/use_tree.rs, crates/hir/src/visitor.rs, crates/parser2/src/ast/expr.rs, crates/parser2/src/ast/stmt.rs, crates/parser2/src/parser/expr.rs, crates/parser2/src/parser/stmt.rs, crates/parser2/src/syntax_kind.rs, crates/parser2/test_files/syntax_node/stmts/assign.snap, crates/parser2/test_files/syntax_node/stmts/for.snap, crates/parser2/test_files/syntax_node/stmts/let.snap, crates/parser2/test_files/syntax_node/stmts/while.snap
resolves #875 
What was wrong?
The new parser (v2 branch) wrongly supposes the assignment destination is a pattern, but it should be an expression.
How was it fixed?
change Assign and augassign to expressions
=>  v2 parser: change assignment's lhs to expression

crates/hir/src/hir_def/pat.rs, crates/hir/src/hir_def/path.rs, crates/hir/src/lower/pat.rs, crates/hir/src/span/pat.rs, crates/hir/src/visitor.rs, crates/parser2/src/ast/pat.rs, crates/parser2/src/parser/pat.rs
This PR restricts 
1. the `mut` keyword occurrence in a pattern only before `Path`,
2. Add a field to `Hir::Pat::Path` to indicate the mutability of the path.
The main reason for the change was that I hesitated to make all HIR pattern kinds include mutability flags.
=> parser: Allow `mut` occurrence only in path pattern

crates/mir/src/analysis/domtree.rs, docs/src/spec/items/functions/context.md, docs/src/user-guide/tutorials/auction.md
=> chore: fix typos

crates/analyzer/src/traversal/expressions.rs, crates/hir-analysis/src/ty/constraint_solver.rs, crates/hir-analysis/src/ty/def_analysis.rs, crates/hir-analysis/src/ty/ty_check/callable.rs, crates/hir-analysis/src/ty/ty_check/env.rs, crates/hir-analysis/src/ty/ty_check/expr.rs, crates/hir-analysis/src/ty/ty_check/mod.rs, crates/hir-analysis/src/ty/ty_def.rs, crates/hir-analysis/test_files/constraints/specialized.fe, crates/hir-analysis/tests/constraints.rs, crates/uitest/fixtures/ty_check/method_bound/specialized.fe, crates/uitest/fixtures/ty_check/method_bound/specialized.snap
I broke the constraint solver when I introduced `Binder`.
This PR also adds the `Callable` information in the type checker, which will be necessary for MIR-lowering and the WF check for types that are implicitly introduced in method resolution.
=> Fix incorrect instantiation in constraint solving

.devcontainer/devcontainer.json
There is no support for Devcontainer
Added `.devcontainer/devcontainer.json` file.
=> Add support for development in both Docker and Github Codespace.

docs/src/std/precompiles.md
replaced a dead link to the eth whitepaper
=> dead link fix

crates/common2/src/diagnostics.rs, crates/fe/src/task/test.rs, crates/hir-analysis/src/lib.rs, crates/hir-analysis/src/ty/canonical.rs, crates/hir-analysis/src/ty/trait_resolution/mod.rs, crates/hir-analysis/src/ty/trait_resolution/proof_forest.rs, crates/hir-analysis/src/ty/unify.rs, crates/uitest/fixtures/ty/trait_bound/coinductive.fe, crates/uitest/fixtures/ty/trait_bound/coinductive.snap, docs/book.toml
This PR ensures the termination in trait solving by adding a bound on type depth.
As the comments in the code describe, we'd need to revisit the trait solver when v2 is deployed.
This limitation doesn't break the soundness of the trait solver itself, but in some cases, users might need to add extra type annotations in their code.
=> Ensure termination in trait solving

crates/codegen/src/yul/isel/inst_order.rs, crates/hir-analysis/src/ty/def_analysis.rs, crates/hir-analysis/src/ty/trait_resolution/proof_forest.rs, crates/uitest/fixtures/ty/trait_bound/occurence_check.fe, crates/uitest/fixtures/ty/trait_bound/occurence_check.snap
This PR fixes a bug of missing an occurrence check in the proof tree implementation.
=> Fix missing occurence check

crates/language-server/editors/vscode/src/extension.ts, crates/language-server/src/lsp_actor/mod.rs
The language server was crashing in stdio mode.  It turned out there was a `println` statement somewhere clogging up stdio, which should be reserved for JSON-RPC messages when running the language server in stdio mode.
I just changed the `println` to a `debug` statement.  The VSCode extension now uses stdio without problems.  This will make it easier to support other editors.
=> Fix language server in stdio mode

Cargo.lock
https://rustsec.org/advisories/RUSTSEC-2024-0357
Also updated yanked crate `bytes`.
=> fix crate vulnerabilities

crates/hir-analysis/src/name_resolution/import_resolver.rs, crates/hir-analysis/src/name_resolution/name_resolver.rs, crates/hir/src/hir_def/item.rs, crates/hir/src/hir_def/scope_graph.rs, crates/hir/src/lower/item.rs, crates/hir/src/span/item.rs, crates/language-server/src/functionality/hover.rs, crates/language-server/src/functionality/item_info.rs, crates/parser2/src/ast/item.rs, crates/parser2/src/parser/item.rs, crates/parser2/test_files/syntax_node/items/enums.fe, crates/parser2/test_files/syntax_node/items/enums.snap
Depends on #1033 
1. Fix missing attributes parsing/lowering
2. Add the `FromScope` trait for a simple resolution from scope id to type `T`
3. Tweak LSP to display the docstrings of some non-item HIR nodes.
=> Parse attrs

crates/hir-analysis/src/ty/diagnostics.rs, crates/hir-analysis/src/ty/ty_check/env.rs, crates/hir-analysis/src/ty/ty_check/pat.rs, crates/uitest/fixtures/ty_check/aug_assign.snap, crates/uitest/fixtures/ty_check/binary.snap, crates/uitest/fixtures/ty_check/call.fe, crates/uitest/fixtures/ty_check/call.snap, crates/uitest/fixtures/ty_check/index.snap, crates/uitest/fixtures/ty_check/pat/duplicated_binding.fe, crates/uitest/fixtures/ty_check/pat/duplicated_binding.snap, crates/uitest/fixtures/ty_check/pat/record.snap, crates/uitest/fixtures/ty_check/unary.snap
Cherry picked from #1010 with some small changes. I also modified some other diagnostic messages.
=> Add missing check for duplicated binding in same pattern

Cargo.lock, Cargo.toml, crates/hir-analysis/src/ty/ty_def.rs, crates/hir/src/hir_def/item.rs, crates/hir/src/hir_def/mod.rs, crates/hir/src/lib.rs
Salsa 3 supports tracked methods, so I inlined the standalone tracked `_impl` functions. No functionality changes.
=> Bump salsa to latest (includes accumulator bugfix), and use salsa::tracked methods instead of separate _impl fns

.github/workflows/main.yml, Cargo.lock, crates/bench/Cargo.toml, crates/bench/benches/analysis.rs, crates/bench/src/main.rs
Three simple benchmarks so far:
- analyze `library/core` (which is quite small right now; this will be more useful as the core lib grows)
- parse all fe files in uitest/fixtures/
- parse and analyze all fe files in uitest/fixtures
```
cd crates/bench
cargo bench
```
```
analysis/analyze corelib
time:   [1.2870 ms 1.2906 ms 1.2946 ms]
change: [-0.3730% +0.0087% +0.4142%] (p = 0.97 > 0.05)
No change in performance detected.
Found 10 outliers among 100 measurements (10.00%)
8 (8.00%) high mild
2 (2.00%) high severe
analysis/uitest parsing time:   [1.6903 ms 1.6949 ms 1.6996 ms]
change: [-0.2576% +0.0639% +0.3805%] (p = 0.71 > 0.05)
No change in performance detected.
analysis/uitest diagnostics
time:   [28.317 ms 28.406 ms 28.502 ms]
change: [-0.5731% -0.0404% +0.4849%] (p = 0.88 > 0.05)
No …
```
=> Add analysis benchmarks

crates/driver/src/lib.rs
replaces #1059
This PR ensures that `fe check` command exits with code 1 when errors are detected, preventing silent failures.
This changes can help building CI automations [like this one](https://github.com/Turupawn/fe-examples) that I'm building now.
=> fix: Return exit code 1 when `fe check` encounters errors (continuation)

Cargo.lock, crates/bench/Cargo.toml, crates/bench/benches/analysis.rs, crates/common/Cargo.toml, crates/common/src/input.rs, crates/driver/Cargo.toml, crates/driver/src/db.rs, crates/driver/src/lib.rs, crates/hir-analysis/tests/corelib.rs, crates/language-server/Cargo.toml, crates/language-server/src/backend/workspace.rs, crates/language-server/test_files/goto.fe, crates/language-server/test_files/goto.snap, crates/uitest/Cargo.toml, crates/uitest/fixtures/ty_check/method_selection/require_explicit_import.snap, crates/uitest/tests/name_resolution.rs
Using rust-embed and moved static core setup to `common::input`. Atm users get an error when goto selecting something in the core library.
=> Core library support in the language server.

crates/common/src/core.rs, crates/common/src/file/mod.rs, crates/common/src/ingot.rs, crates/common/src/urlext.rs, crates/driver/src/lib.rs, crates/hir-analysis/tests/corelib.rs, crates/hir-analysis/tests/test_db.rs, crates/hir/src/hir_def/mod.rs, crates/hir/src/hir_def/module_tree.rs, crates/language-server/src/backend/workspace.rs, crates/language-server/src/functionality/goto.rs, crates/language-server/src/functionality/handlers.rs, crates/test-utils/src/url_utils.rs, crates/uitest/tests/name_resolution.rs, crates/uitest/tests/parser.rs, crates/uitest/tests/ty.rs, crates/uitest/tests/ty_check.rs, wasm_cleanup.patch
This fixes a salsa cycle caused by accidentally linking ingot child file paths to the tracked `Ingot` struct creation.  What I learned is that salsa tracked structs are linked to the execution Id of the query (derived from the arguments) that runs their constructor, not strictly to their Id fields.  That's very subtle and I had no idea.
The fix was to ensure that `Ingot` tracked structs are created in a query whose arguments have a 1:1 relationship with the ingot, i.e. the base URL.
- Ensure 1:1 relationship between `Ingot` and the ingot base URL
- WASM doesn't support std `Path`, so this PR includes some shims for `Path` --> `Url` 
- Initialization of `Ingot::files` query... after fixing the salsa cycle, two ambiguous resolution diagnostics weren't collected unless the files query was …
=> Fix import resolver cycle

crates/common/src/core.rs, crates/common/src/file/mod.rs, crates/common/src/ingot.rs, crates/driver/src/lib.rs, crates/hir-analysis/tests/corelib.rs, crates/hir-analysis/tests/pattern_matching.rs, crates/hir/src/hir_def/mod.rs, crates/hir/src/hir_def/module_tree.rs, crates/language-server/src/backend/workspace.rs, crates/language-server/src/functionality/goto.rs, crates/language-server/src/functionality/handlers.rs, crates/uitest/fixtures/ty_check/method_selection/require_explicit_import.snap
(followup to #1102)
Previously `Ingot` instances were salsa inputs that held onto their files.  This meant that changing the file simply invalidated the inputs and correctly triggered recomputation of the module tree. 
In the initial file management refactor PR #1081, I'd replaced access to the salsa input `files` accessor with the new `files` query, but what I didn't understand at the time is that the module tree builder wasn't fully salsa tracked, and some of those the untracked calls to `files` relied on the fact that the whole `InputIngot` would be invalidated when `InputIngot::files` changed.
As a hack I'd added `let _ = ingot.files(db)` on the new `Ingot` tracked struct constructors... but what really needed to be done was to ensure all of the calls to `ingot.files` in the module …
=> Fix salsa module tree salsa tracking

.github/workflows/main.yml
Updates actions/checkout@v3 to actions/checkout@v5 across CI workflows.
Upgrade to actions/checkout@v5 for improved performance and stability.
Reference:
Latest version: https://github.com/actions/checkout/releases/tag/v5.0.0
=> chore: update GitHub actions in CI workflows

crates/hir-analysis/src/diagnostics.rs, crates/hir-analysis/src/name_resolution/path_resolver.rs, crates/hir-analysis/src/ty/def_analysis.rs, crates/hir-analysis/src/ty/diagnostics.rs, crates/hir-analysis/src/ty/mod.rs, crates/hir-analysis/src/ty/trait_lower.rs, crates/hir-analysis/src/ty/ty_lower.rs, crates/hir-analysis/test_files/ty_check/default_generic_struct.fe, crates/hir-analysis/test_files/ty_check/default_generic_struct.snap, crates/hir-analysis/test_files/ty_check/default_generic_trait.fe, crates/hir-analysis/test_files/ty_check/default_generic_trait.snap, crates/hir-analysis/test_files/ty_check/default_generic_type_alias.fe, crates/hir-analysis/test_files/ty_check/default_generic_type_alias.snap, crates/hir/src/hir_def/item.rs, crates/hir/src/hir_def/params.rs, crates/hir/src/lower/params.rs, crates/parser/src/ast/param.rs, crates/parser/src/parser/param.rs, crates/parser/test_files/syntax_node/items/trait.fe, crates/parser/test_files/syntax_node/items/trait.snap, crates/uitest/fixtures/ty/def/alias_duplicate_param.fe, crates/uitest/fixtures/ty/def/alias_duplicate_param.snap, crates/uitest/fixtures/ty/def/alias_missing_generic_arg.fe, crates/uitest/fixtures/ty/def/alias_missing_generic_arg.snap, crates/uitest/fixtures/ty/def/alias_too_many_args.fe, crates/uitest/fixtures/ty/def/alias_too_many_args.snap, crates/uitest/fixtures/ty_check/default_generic_forward_ref.fe, crates/uitest/fixtures/ty_check/default_generic_forward_ref.snap, crates/uitest/fixtures/ty_check/default_generic_non_trailing.fe, crates/uitest/fixtures/ty_check/default_generic_non_trailing.snap
```
struct Foo<T = i32> {
inner: T
}
trait Add<T: Self> {
type Output = Self
fn add(self, _ other: T) -> Self::Output
}
```
I also moved the type alias analysis into DefAnalyzer, where the other item definitions are analyzed. This fixes some missing type alias diagnostics.
=> Add support for generic parameter defaults
