argotorg/fe

.github/workflows/main.yml
compiler/src/abi/builder.rs
compiler/src/abi/elements.rs
compiler/src/errors.rs
compiler/src/yul/mappers/declarations.rs
compiler/src/yul/mod.rs
compiler/src/yul/runtime/abi.rs
parser/src/parsers.rs

Previously, CI only showed clippy warnings but did not fail on them. There were also a bunch of places that raised warnings.
1. Told Clippy to treat warnings as errors (`-- -D warnings`)
2. Resolved all warnings by following clippys suggestions.

Fail build on clippy warnings

---

compiler/src/yul/mappers/assignments.rs
compiler/src/yul/mappers/expressions.rs
compiler/tests/evm_contracts.rs
compiler/tests/fixtures/return_bitwiseand_u256.vy
compiler/tests/fixtures/return_bitwiseor_u256.vy
compiler/tests/fixtures/return_bitwiseshl_u256.vy
compiler/tests/fixtures/return_bitwiseshr_u256.vy
compiler/tests/fixtures/return_bitwisexor_u256.vy
compiler/tests/fixtures/return_mod_u256.vy
compiler/tests/fixtures/return_pow_u256.vy

Support for a bunch of binary operations was still missing.
Added support + tests

Implement more binary operations

---

.github/PULL_REQUEST_TEMPLATE.md
spec/index.md

As stated in #40 we need to start writing a language specification.
Not fixed but wanted to break ground after implementing the arithmetic operations.

Start language specification

---

README.md
docs/build.md

Updated goals with our latest progress and added erc20 as a new short-term goal. Also provided build instructions.

Readme goals updates and build doc.

---

logo/README.md

Change URL of logo in Readme

---

spec/index.md

Data layout was not specified.
Described how each data type should be stored in each location.

Data layout spec.

---

semantics/src/traversal/functions.rs

lint was failing due to new formatting

---

compiler/tests/fixtures/static_string.fe

This got accidentally commited as part of cutting the release.
Removed file

Remote accidentially commited file

---

analyzer/src/errors.rs
analyzer/src/namespace/scopes.rs
analyzer/src/traversal/assignments.rs
analyzer/src/traversal/contracts.rs
analyzer/src/traversal/declarations.rs
analyzer/src/traversal/expressions.rs
analyzer/src/traversal/functions.rs

Adds semantic error AlreadyDefined to propagate an error in a case of duplicate definitions of functions, variables, etc.

---

.github/workflows/main.yml
Makefile
compiler/src/abi/elements.rs
compiler/src/lib.rs
compiler/src/yul/operations/data.rs
compiler/tests/compile_errors.rs

We recently pinned a specific nightly because it was kind of broken.
Unpinned and adjusted code for latest changes.

Unpin specific nightly

---

compiler/src/yul/mappers/assignments.rs
compiler/src/yul/mappers/expressions.rs
compiler/src/yul/names.rs
compiler/src/yul/runtime/functions/math.rs
compiler/tests/features.rs
compiler/tests/fixtures/features/checked_arithmetic.fe
newsfragments/312.feature.md

Modulo arithmetic isn't checked yet.
Pretty straight forward based on how the previous checks were implemented.

Implement checks for modulo arithmetic

---

analyzer/src/traversal/expressions.rs
compiler/src/yul/mappers/expressions.rs
compiler/tests/features.rs
compiler/tests/fixtures/features/return_msg_sig.fe
compiler/tests/utils.rs
newsfragments/311.feature.md

Implement msg.sig

---

compiler/src/lib.rs

closes #402 
Just needed to return the errors.
Going to merge this once the build finishes, since it's so simple.

Return errors when compiling.

---

docs/src/quickstart/installation.md
newsfragments/439.feature.md
src/main.rs

--optimize is now an option,--optimize=true is default

Make --optimize the default #439

---

Makefile

Fix cargo pkgid invocation in release command

---

crates/analyzer/tests/snapshots/analysis__uniswap.snap
crates/test-files/fixtures/demos/uniswap.fe

There's a comment in the Uniswap demo implementation that was no longer true.
Removed comment

Remove outdated comment

---

README.md

Update snippet in README.md to latest syntax

---

README.md
docs/src/release_notes.md
website/CNAME
website/index.html

Change Domain to fe-lang.org

---

docs/src/quickstart/first_contract.md
docs/src/quickstart/installation.md
docs/src/release_notes.md
docs/src/spec/expr_comparison_operators.md
docs/src/spec/index.md
docs/src/spec/tokens.md
docs/src/spec/visibility_and_privacy.md

There are some typos
Use the right words.

fix the typos

---

crates/analyzer/tests/snapshots/analysis__structs.snap
crates/test-files/fixtures/features/structs.fe
crates/tests/src/features.rs

We haven't had a test that calls a method with a struct, sets it to storage and reads it again.
Added such test.

Add test that sets and reads to and from storage

---

crates/test-files/fixtures/differential/math_u8.fe
crates/test-files/fixtures/differential/math_u8.sol
crates/test-files/fixtures/differential/storage_and_memory.fe
crates/test-files/fixtures/differential/storage_and_memory.sol
crates/test-utils/src/lib.rs
crates/tests/src/differential.rs
crates/tests/src/features.rs
crates/tests/src/solidity.rs

Need more differential contract fuzzing
I had these piled up for a while but they were waiting on the fix for array index bounds checking which landed recently. 
Mostly just writing and reading things to and from memory and storage.
It also adds gas tracking (reporting overuse as an error). Our gas usage is astronomic but at least these checks should ensure that we notice if it gets worse. We should screw the bounds tighter when we optimize our code-.

More differential contract fuzzing

---

crates/analyzer/src/db.rs
crates/analyzer/src/db/queries/contracts.rs
crates/analyzer/src/db/queries/functions.rs
crates/analyzer/src/namespace/items.rs
crates/analyzer/src/traversal/expressions.rs
crates/analyzer/tests/errors.rs
crates/analyzer/tests/snapshots/errors__call_call_on_external_contract.snap
crates/analyzer/tests/snapshots/errors__call_call_on_self.snap
crates/analyzer/tests/snapshots/errors__call_duplicate_def.snap
crates/analyzer/tests/snapshots/errors__call_with_pub_fns.snap
crates/analyzer/tests/snapshots/errors__call_wrong_return_type.snap
crates/analyzer/tests/snapshots/errors__init_call_on_self.snap
crates/analyzer/tests/snapshots/errors__init_duplicate_def.snap
crates/lowering/src/mappers/contracts.rs
crates/test-files/fixtures/compile_errors/call_call_on_external_contract.fe
crates/test-files/fixtures/compile_errors/call_call_on_self.fe
crates/test-files/fixtures/compile_errors/call_duplicate_def.fe
crates/test-files/fixtures/compile_errors/call_with_pub_fns.fe
crates/test-files/fixtures/compile_errors/call_wrong_return_type.fe
crates/test-files/fixtures/features/call_fn.fe
crates/test-utils/src/lib.rs
crates/tests/src/features.rs
crates/yulgen/src/db/queries/contracts.rs
crates/yulgen/src/runtime/abi_dispatcher.rs
crates/yulgen/tests/snapshots/yulgen__abi_dispatcher.snap
newsfragments/622.feature.md

contract `__call__` function  

---

Cargo.lock
crates/test-utils/Cargo.toml
crates/yulc/Cargo.toml

bump solc to 0.8.11

---

crates/parser/src/grammar/expressions.rs

Parser panicked on unary plus https://github.com/ethereum/fe/issues/443
Added error message when unary plus is hit.

Handle parser panic on unary plus

---

crates/analyzer/src/context.rs

I broke expensive tests due to inappropriate annotations on example code blocks. Sorry.
Changed annotations from `ignore` to `fe`.

Fix expensive tests

---

crates/fe/src/main.rs

Currently, `Fe` compiler can't compiler ingot directories because the loader tries to load source codes from a directory that `Walkdir` returns.
This fix isn't relevant to spec.
This is a trivial change.

Fix failures to load ingot

---

crates/analyzer/src/traversal/expressions.rs
crates/analyzer/tests/errors.rs
crates/analyzer/tests/snapshots/errors__overflow_u128_neg.snap
crates/analyzer/tests/snapshots/errors__overflow_u16_neg.snap
crates/analyzer/tests/snapshots/errors__overflow_u256_neg.snap
crates/analyzer/tests/snapshots/errors__overflow_u32_neg.snap
crates/analyzer/tests/snapshots/errors__overflow_u64_neg.snap
crates/analyzer/tests/snapshots/errors__overflow_u8_neg.snap
crates/analyzer/tests/snapshots/errors__unary_always_mismatch_type_case_1.snap
crates/analyzer/tests/snapshots/errors__unary_always_mismatch_type_case_2.snap
newsfragments/651.bugfix.md

Unary minus mismatch type

---

website/index.html

Set new blog URL

---

crates/analyzer/src/db.rs
crates/analyzer/src/errors.rs
crates/analyzer/src/namespace/scopes.rs
crates/codegen/src/db.rs
crates/common/src/panic.rs
crates/mir/src/db.rs
crates/parser/src/lexer/token.rs
website/index.html

On FireFox we currently fail to detect the platform (windows, linux, mac).
User `navigator.userAgent` instead of `navigator.appVersion`
´

Fix platform detection in Firefox

---

crates/analyzer/src/db/queries/ingots.rs
crates/analyzer/src/namespace/items.rs
crates/analyzer/src/traversal/functions.rs
crates/analyzer/src/traversal/pattern_analysis.rs
crates/fe/src/task/check.rs
crates/parser/src/lexer.rs
crates/parser/src/parser.rs
docs/book.toml

CI Job fails because goerli faucet has our CI job blocked
Exclude from linkcheck

Exclude goerli faucet from link check

---

website/index.html

Update website example to match latest Fe

---

crates/analyzer/src/db/queries/contracts.rs
crates/analyzer/src/db/queries/module.rs
crates/analyzer/src/errors.rs
crates/analyzer/src/namespace/items.rs
crates/analyzer/src/traversal/assignments.rs
crates/analyzer/src/traversal/borrowck.rs
crates/analyzer/src/traversal/expressions.rs
crates/analyzer/src/traversal/functions.rs
crates/analyzer/src/traversal/matching_anomaly.rs
crates/analyzer/src/traversal/types.rs
crates/analyzer/src/traversal/utils.rs
crates/codegen/src/yul/isel/context.rs
crates/common/src/utils/keccak.rs
crates/mir/src/lower/pattern_match/decision_tree.rs
crates/test-utils/src/lib.rs
crates/tests/src/solidity.rs

Make clippy happy

---

docs/src/quickstart/projects.md

Expands the information available in the `quickstart/projects` page.

[website/docs]: update projects page

---

docs/src/user-guide/installation.md

Adds note to `src/user-guide/installation.md` about installing using homebrew

[website/docs]: add note on homebrew to install page

---

docs/src/development/release.md
docs/src/user-guide/installation.md
docs/src/user-guide/projects.md

Fix minor typos

---

Cargo.lock
crates/abi/src/types.rs
crates/codegen/src/db.rs
crates/codegen/src/db/queries/abi.rs
crates/driver/src/lib.rs
crates/fe/src/task/test.rs
crates/test-runner/Cargo.toml
crates/test-runner/src/lib.rs
crates/tests/src/lib.rs
newsfragments/933.feature.md

Test logging. Events are decoded and logs that do not match an event signature or cannot be decoded are printed in their raw form.

Test logging

---

README.md
website/index.html

At Devconnect people notified us that some wording on our website was out of date. This is a quick and dirty job to make it less bad.

Update some out of date wording

---

docs/src/SUMMARY.md
docs/src/release_notes.md
docs/src/std/precompiles.md
newsfragments/980.feature.md

chore: fix some comments

---

crates/hir-analysis/src/ty/ty_check/callable.rs
crates/hir-analysis/src/ty/ty_check/expr.rs
crates/hir-analysis/test_files/ty_check/method.fe
crates/hir-analysis/test_files/ty_check/method.snap

This fixes an incorrect label assertion bug. 
@g-r-a-n-t

Fix label assertion bug

---

crates/hir-analysis/src/name_resolution/import_resolver.rs
crates/hir-analysis/src/ty/trait_def.rs
crates/hir-analysis/src/ty/ty_check/expr.rs
crates/hir-analysis/test_files/ty_check/method/generics.fe
crates/hir-analysis/test_files/ty_check/method/generics.snap
crates/language-server/src/diagnostics.rs
crates/mir/src/analysis/loop_tree.rs
crates/uitest/fixtures/ty_check/method_bound/generics.fe
crates/uitest/fixtures/ty_check/method_bound/generics.snap

This PR fixes the bug that @g-r-a-n-t  reported today and makes clippy(v1.78.0) happy.
(I want to clean up the ty-check test; the output is really messy...). But for now, I want to keep it as is.

Fix trait method selection

---

funding.json

This is required for the 4th optimism retopgf round.

op retro fund verification

---

crates/language-server/src/functionality/diagnostics.rs
crates/language-server/src/functionality/handlers.rs
crates/language-server/src/server.rs
crates/language-server/src/util.rs

- more analysis passes in the language server
- default fallback handlers for unused LSP notifications/events
- graceful handling of sub-diagnostics with no spans

additional LSP diagnostics + fixups

---

crates/common2/src/indexmap.rs

Fix the bug in `impl Update for IndexMap`

Fix `salsa::Update` impl for `IndexMap`

---

crates/hir/src/lower/scope_builder.rs

Transferred from https://github.com/sbillig/fe/pull/1.

Fix missing id stack management in `leave_item_scope`

---

crates/common2/src/diagnostics.rs
crates/hir-analysis/src/ty/diagnostics.rs
crates/language-server/src/functionality/diagnostics.rs
crates/language-server/src/functionality/goto.rs
crates/language-server/src/util.rs
crates/uitest/fixtures/ty/def/generic_param_conflict.snap

Depends on #1035 
* Display Secondary diagnostics as a `HINT`
* Add `DiagnosticRelatedInformation` to LSP diag if the diag is secondary to show the primary location of the problem.  
* Add missing analysis passes

Minor LSP improvement

---

crates/driver/src/diagnostics.rs
crates/hir-analysis/src/diagnostics.rs
crates/hir-analysis/src/ty/diagnostics.rs
crates/hir-analysis/src/ty/ty_check/callable.rs
crates/hir-analysis/src/ty/ty_check/expr.rs
crates/hir-analysis/src/ty/ty_check/mod.rs
crates/hir-analysis/src/ty/ty_check/pat.rs
crates/hir-analysis/src/ty/ty_check/path.rs
crates/hir-analysis/test_files/ty_check/record_init.fe
crates/hir-analysis/test_files/ty_check/record_init.snap
crates/hir/src/hir_def/item.rs
crates/hir/src/span/expr.rs
crates/uitest/fixtures/ty_check/arg_count_mismatch.fe
crates/uitest/fixtures/ty_check/arg_count_mismatch.snap
crates/uitest/fixtures/ty_check/call_field.fe
crates/uitest/fixtures/ty_check/call_field.snap
crates/uitest/fixtures/ty_check/generic_arg_mismatch.snap

Some minor diagnostic improvements.
(I was going to make more changes, but I'm distracted by other things at the moment; marking this as ready.)

Diagnostic improvements

---

library/core/fe.toml

core metadata

---

crates/common/src/tree.rs
crates/driver/src/lib.rs
crates/fe/src/check.rs
crates/fe/src/tree.rs
crates/hir-analysis/src/diagnostics.rs
crates/hir/src/lower/use_tree.rs
crates/resolver/src/files.rs

I apologise for issuing the PR without running the formatter the other day.
This pr should resolve all formatting errors.

fix: format error
